const products = {
  cpu: [
    
    {
      id: "cpu001",
      ten: "Intel Core i9-13900K",
      hang: "Intel",
      gia: 14000000,
      thong_so: {
        cores: 24,
        threads: 32,
        baseClock: "3.0 GHz",
        boostClock: "5.8 GHz",
        socket: "LGA 1700",
        cache: "36MB",
      },
      so_luong: 50,
      mo_ta:
        "Intel Core i9-13900K là bộ vi xử lý hàng đầu dành cho game thủ, nhà sáng tạo nội dung và chuyên gia cần hiệu năng vượt trội. Với 24 nhân (8 nhân hiệu năng cao, 16 nhân tiết kiệm điện) và 32 luồng, sản phẩm này vượt trội trong đa nhiệm, dựng hình 3D và chơi game nặng. Tốc độ cơ bản 3.0 GHz và tăng tốc tối đa 5.8 GHz giúp xử lý nhanh các ứng dụng như Adobe After Effects, Blender và các tựa game AAA. Socket LGA 1700 tương thích với bo mạch chủ Intel 600/700-series, hỗ trợ RAM DDR5 và PCIe 5.0, đảm bảo khả năng nâng cấp trong tương lai. Kiến trúc lai tối ưu hiệu suất và tiết kiệm năng lượng, lý tưởng cho ép xung. Công nghệ Intel Turbo Boost Max 3.0 và Thermal Velocity Boost tăng cường hiệu năng khi tải nặng. Dù bạn lắp ráp PC chơi game hay máy trạm dựng phim, i9-13900K mang lại tốc độ và độ tin cậy đỉnh cao.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["chơi game", "cao cấp", "intel", "ép xung"],
      rating: 4.9,
      reviewCount: 320,
      khuyen_mai: "Tặng keo tản nhiệt Noctua NT-H1",
      images: [
        "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/_/t_i_xu_ng_-_2023-02-09t224950.288_1_1_1.png",
        "images/cpu/i9-13900k-2.jpg",
      ],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-10-20",
      thiet_bi_tuong_thich: ["Bo mạch chủ Intel 600/700-series"],
      tinh_nang: [
        "Kiến trúc lai",
        "Turbo Boost Max 3.0",
        "Hỗ trợ PCIe 5.0",
        "Hỗ trợ DDR5",
      ],
      danh_muc: "CPU",
    },
    {
      id: "cpu002",
      ten: "Intel Core i7-13700K",
      hang: "Intel",
      gia: 12000000,
      thong_so: {
        cores: 16,
        threads: 24,
        baseClock: "3.4 GHz",
        boostClock: "5.4 GHz",
        socket: "LGA 1700",
        cache: "30MB",
      },
      so_luong: 40,
      mo_ta:
        "Intel Core i7-13700K là bộ vi xử lý mạnh mẽ dành cho game thủ và nhà sáng tạo nội dung. Với 16 nhân (8 nhân hiệu năng cao, 8 nhân tiết kiệm điện) và 24 luồng, CPU này mang lại hiệu năng vượt trội cho các tác vụ nặng như chơi game AAA, chỉnh sửa video 4K và mô phỏng 3D. Tốc độ cơ bản 3.4 GHz và tăng tốc tối đa 5.4 GHz đảm bảo xử lý nhanh chóng các ứng dụng như Adobe Premiere Pro và Blender. Socket LGA 1700 tương thích với bo mạch chủ Intel 600/700-series, hỗ trợ RAM DDR5 và PCIe 5.0, giúp nâng cấp dễ dàng trong tương lai. Đây là lựa chọn lý tưởng cho người dùng cần hiệu năng cao và độ tin cậy.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["gaming", "Intel", "hiệu năng cao"],
      rating: 4.8,
      reviewCount: 300,
      khuyen_mai: "Giảm 10% khi mua kèm mainboard Z790",
      images: ["images/cpu/i7-13700k-1.jpg", "images/cpu/i7-13700k-2.jpg"],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-10-20",
      thiet_bi_tuong_thich: ["Bo mạch chủ Intel 600/700-series"],
      tinh_nang: [
        "Kiến trúc lai",
        "Hỗ trợ PCIe 5.0",
        "Hỗ trợ DDR5",
        "Intel UHD Graphics",
      ],
      danh_muc: "CPU",
    },
    {
      id: "cpu003",
      ten: "AMD Ryzen 9 7950X3D",
      hang: "AMD",
      gia: 16500000,
      thong_so: {
        cores: 16,
        threads: 32,
        baseClock: "4.2 GHz",
        boostClock: "5.7 GHz",
        socket: "AM5",
        cache: "144MB",
      },
      so_luong: 30,
      mo_ta:
        "AMD Ryzen 9 7950X3D là bộ vi xử lý tiên tiến dành cho game thủ và nhà sáng tạo, tích hợp công nghệ 3D V-Cache độc quyền của AMD. Với 16 nhân, 32 luồng và bộ nhớ đệm L3 khổng lồ 144MB, CPU này giảm độ trễ, tối ưu cho chơi game và xử lý tác vụ nặng như dựng hình 3D hay mô phỏng. Tốc độ cơ bản 4.2 GHz và tăng tốc tối đa 5.7 GHz đảm bảo hiệu năng mượt mà với các game AAA và phần mềm như Adobe Premiere Pro. Socket AM5 hỗ trợ RAM DDR5 và PCIe 5.0, giúp tương thích với công nghệ mới nhất. Đồ họa Radeon tích hợp hỗ trợ hiển thị cơ bản, trong khi khả năng ép xung thu hút người dùng chuyên sâu. Với hiệu suất cao và tiết kiệm điện, Ryzen 9 7950X3D là lựa chọn hoàn hảo cho PC chơi game hoặc máy trạm sáng tạo, mang lại tốc độ và độ tin cậy vượt trội.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["chơi game", "3D V-Cache", "AMD", "sáng tạo nội dung"],
      rating: 4.8,
      reviewCount: 200,
      khuyen_mai: "Tặng quạt AMD Wraith Prism",
      images: [
        "images/cpu/ryzen-7950x3d-1.jpg",
        "images/cpu/ryzen-7950x3d-2.jpg",
      ],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2023-02-28",
      thiet_bi_tuong_thich: ["Bo mạch chủ AM5"],
      tinh_nang: [
        "3D V-Cache",
        "Hỗ trợ PCIe 5.0",
        "Hỗ trợ DDR5",
        "Đồ họa tích hợp",
      ],
      danh_muc: "CPU",
    },
    {
      id: "cpu004",
      ten: "Intel Core i5-13600K",
      hang: "Intel",
      gia: 8500000,
      thong_so: {
        cores: 14,
        threads: 20,
        baseClock: "3.5 GHz",
        boostClock: "5.1 GHz",
        socket: "LGA 1700",
        cache: "24MB",
      },
      so_luong: 45,
      mo_ta:
        "Intel Core i5-13600K là CPU tầm trung mạnh mẽ, lý tưởng cho gaming và công việc đa nhiệm...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["gaming", "Intel", "tầm trung", "đa nhiệm"],
      rating: 4.7,
      reviewCount: 180,
      khuyen_mai: "Giảm 500.000đ khi mua kèm mainboard",
      images: ["images/cpu/i5-13600k-1.jpg", "images/cpu/i5-13600k-2.jpg"],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-10-20",
      thiet_bi_tuong_thich: ["Bo mạch chủ Intel 600/700-series"],
      tinh_nang: [
        "Kiến trúc lai",
        "Intel UHD Graphics",
        "Hỗ trợ PCIe 5.0",
        "Hỗ trợ DDR5",
      ],
      danh_muc: "CPU",
    },
    {
      id: "cpu005",
      ten: "AMD Ryzen 5 7600X",
      hang: "AMD",
      gia: 7500000,
      thong_so: {
        cores: 6,
        threads: 12,
        baseClock: "4.7 GHz",
        boostClock: "5.3 GHz",
        socket: "AM5",
        cache: "38MB",
      },
      so_luong: 55,
      mo_ta:
        "AMD Ryzen 5 7600X là CPU gaming hiệu năng cao với kiến trúc Zen 4...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["gaming", "AMD", "Zen 4", "tầm trung"],
      rating: 4.6,
      reviewCount: 150,
      khuyen_mai: "Tặng tản nhiệt AMD stock cooler",
      images: [
        "images/cpu/ryzen5-7600x-1.jpg",
        "images/cpu/ryzen5-7600x-2.jpg",
      ],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-09-27",
      thiet_bi_tuong_thich: ["Bo mạch chủ AM5"],
      tinh_nang: ["Zen 4", "RDNA 2 Graphics", "PCIe 5.0", "DDR5"],
      danh_muc: "CPU",
    },
    {
      id: "cpu006",
      ten: "Intel Core i7-13700KF",
      hang: "Intel",
      gia: 9500000,
      thong_so: {
        cores: 16,
        threads: 24,
        baseClock: "3.4 GHz",
        boostClock: "5.4 GHz",
        socket: "LGA 1700",
        cache: "30MB",
      },
      so_luong: 35,
      mo_ta:
        "Phiên bản không tích hợp đồ họa của i7-13700K, lý tưởng cho các hệ thống sử dụng card đồ họa rời...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["gaming", "Intel", "cao cấp"],
      rating: 4.8,
      reviewCount: 140,
      khuyen_mai: "Tặng kèm tản nhiệt DeepCool AK620",
      images: ["images/cpu/i7-13700kf-1.jpg", "images/cpu/i7-13700kf-2.jpg"],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-10-20",
      thiet_bi_tuong_thich: ["Bo mạch chủ Intel 600/700-series"],
      tinh_nang: ["Kiến trúc lai", "Raptor Lake", "PCIe 5.0", "DDR5"],
      danh_muc: "CPU",
    },
    {
      id: "cpu007",
      ten: "AMD Ryzen 7 7700X",
      hang: "AMD",
      gia: 9000000,
      thong_so: {
        cores: 8,
        threads: 16,
        baseClock: "4.5 GHz",
        boostClock: "5.4 GHz",
        socket: "AM5",
        cache: "40MB",
      },
      so_luong: 40,
      mo_ta: "CPU 8 nhân mạnh mẽ cho gaming và sáng tạo nội dung...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["gaming", "AMD", "sáng tạo"],
      rating: 4.7,
      reviewCount: 165,
      khuyen_mai: "Tặng Windows 11 Pro bản quyền",
      images: [
        "images/cpu/ryzen7-7700x-1.jpg",
        "images/cpu/ryzen7-7700x-2.jpg",
      ],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-09-27",
      thiet_bi_tuong_thich: ["Bo mạch chủ AM5"],
      tinh_nang: ["Zen 4", "RDNA 2", "PCIe 5.0", "DDR5"],
      danh_muc: "CPU",
    },
    {
      id: "cpu008",
      ten: "Intel Core i5-13400F",
      hang: "Intel",
      gia: 5500000,
      thong_so: {
        cores: 10,
        threads: 16,
        baseClock: "2.5 GHz",
        boostClock: "4.6 GHz",
        socket: "LGA 1700",
        cache: "20MB",
      },
      so_luong: 60,
      mo_ta: "CPU giá rẻ hiệu năng cao cho gaming và làm việc...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["gaming", "Intel", "giá rẻ"],
      rating: 4.6,
      reviewCount: 200,
      khuyen_mai: "Giảm 300.000đ khi mua kèm main H610",
      images: ["images/cpu/i5-13400f-1.jpg", "images/cpu/i5-13400f-2.jpg"],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2023-01-03",
      thiet_bi_tuong_thich: ["Bo mạch chủ Intel 600/700-series"],
      tinh_nang: ["Raptor Lake", "PCIe 4.0", "DDR4/DDR5"],
      danh_muc: "CPU",
    },
    {
      id: "cpu009",
      ten: "AMD Ryzen 5 7600",
      hang: "AMD",
      gia: 6000000,
      thong_so: {
        cores: 6,
        threads: 12,
        baseClock: "3.8 GHz",
        boostClock: "5.1 GHz",
        socket: "AM5",
        cache: "38MB",
      },
      so_luong: 50,
      mo_ta:
        "Phiên bản tiết kiệm điện của 7600X, phù hợp cho các hệ thống gaming tầm trung...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["gaming", "AMD", "tiết kiệm"],
      rating: 4.5,
      reviewCount: 120,
      khuyen_mai: "Tặng kèm quạt tản nhiệt AMD",
      images: ["images/cpu/ryzen5-7600-1.jpg", "images/cpu/ryzen5-7600-2.jpg"],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2023-01-09",
      thiet_bi_tuong_thich: ["Bo mạch chủ AM5"],
      tinh_nang: ["Zen 4", "RDNA 2", "PCIe 5.0", "DDR5"],
      danh_muc: "CPU",
    },
    {
      id: "cpu010",
      ten: "Intel Core i3-13100F",
      hang: "Intel",
      gia: 3000000,
      thong_so: {
        cores: 4,
        threads: 8,
        baseClock: "3.4 GHz",
        boostClock: "4.5 GHz",
        socket: "LGA 1700",
        cache: "12MB",
      },
      so_luong: 70,
      mo_ta: "CPU entry-level hoàn hảo cho gaming giá rẻ và văn phòng...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["gaming", "Intel", "giá rẻ", "văn phòng"],
      rating: 4.4,
      reviewCount: 180,
      khuyen_mai: "Giảm giá khi mua combo",
      images: ["images/cpu/i3-13100f-1.jpg", "images/cpu/i3-13100f-2.jpg"],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2023-01-03",
      thiet_bi_tuong_thich: ["Bo mạch chủ Intel 600/700-series"],
      tinh_nang: ["Raptor Lake", "PCIe 4.0", "DDR4/DDR5"],
      danh_muc: "CPU",
    },
  ],
  mainboard: [
    {
      id: "mb001",
      ten: "ASUS ROG Strix Z790-E Gaming",
      hang: "ASUS",
      gia: 10000000,
      thong_so: {
        chipset: "Z790",
        socket: "LGA 1700",
        formFactor: "ATX",
        memorySlots: 4,
        maxMemory: "128GB",
        pcieSlots: "1 x PCIe 5.0 x16, 2 x PCIe 4.0 x16",
      },
      so_luong: 20,
      mo_ta:
        "ASUS ROG Strix Z790-E Gaming là bo mạch chủ ATX cao cấp dành cho game thủ và người dùng sử dụng CPU Intel thế hệ 12 và 13. Với chipset Z790 và socket LGA 1700, bo mạch hỗ trợ RAM DDR5 tối đa 128GB và PCIe 5.0 cho GPU và ổ cứng thế hệ mới. Thiết kế VRM mạnh mẽ và tản nhiệt tiên tiến đảm bảo ổn định khi ép xung CPU như i9-13900K. Sản phẩm tích hợp Wi-Fi 6E, Ethernet 2.5Gb và nhiều khe M.2 với tấm tản nhiệt, mang lại tốc độ kết nối và lưu trữ vượt trội. Âm thanh SupremeFX cung cấp trải nghiệm sống động, trong khi đèn RGB tùy chỉnh với Aura Sync tăng tính thẩm mỹ. Phù hợp cho PC chơi game hoặc máy trạm, ROG Strix Z790-E kết hợp độ bền, kết nối và phong cách, là lựa chọn hàng đầu cho hệ thống hiện đại.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["chơi game", "ASUS", "ATX", "ép xung"],
      rating: 4.8,
      reviewCount: 210,
      khuyen_mai: "Giảm 5% khi mua kèm CPU Intel i9",
      images: [
        "images/mainboard/asus-z790-e-1.jpg",
        "images/mainboard/asus-z790-e-2.jpg",
      ],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-10-17",
      thiet_bi_tuong_thich: [
        "CPU Intel thế hệ 12/13",
        "RAM DDR5",
        "GPU PCIe 5.0",
      ],
      tinh_nang: [
        "Wi-Fi 6E",
        "Âm thanh SupremeFX",
        "Đèn RGB Aura Sync",
        "Hỗ trợ PCIe 5.0",
      ],
      danh_muc: "Mainboard",
    },
    {
      id: "mb002",
      ten: "MSI MPG B650 Tomahawk WiFi",
      hang: "MSI",
      gia: 6500000,
      thong_so: {
        chipset: "B650",
        socket: "AM5",
        formFactor: "ATX",
        memorySlots: 4,
        maxMemory: "128GB",
        pcieSlots: "1 x PCIe 4.0 x16, 2 x PCIe 3.0 x1",
      },
      so_luong: 25,
      mo_ta:
        "MSI MPG B650 Tomahawk WiFi là bo mạch chủ ATX giá trị cao dành cho CPU AMD Ryzen 7000-series trên nền tảng AM5. Với chipset B650, sản phẩm hỗ trợ RAM DDR5 tối đa 128GB và PCIe 4.0 cho GPU và ổ cứng NVMe tốc độ cao. Thiết kế VRM bền bỉ và tản nhiệt mở rộng đảm bảo hiệu năng ổn định khi ép xung CPU như Ryzen 9 7950X3D. Bo mạch tích hợp Wi-Fi 6, LAN 2.5Gb và nhiều khe M.2 với tấm tản nhiệt, đáp ứng nhu cầu lưu trữ nhanh. Đèn Mystic Light RGB cho phép tùy chỉnh ánh sáng theo phong cách cá nhân. Âm thanh chất lượng cao hỗ trợ chơi game và phát trực tuyến. Phù hợp cho PC chơi game tầm trung đến cao cấp hoặc máy trạm, MPG B650 Tomahawk WiFi mang lại sự cân bằng giữa hiệu năng, kết nối và giá trị, tương thích với công nghệ mới nhất của AMD.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["chơi game", "MSI", "AM5", "giá trị"],
      rating: 4.7,
      reviewCount: 180,
      khuyen_mai: "Tặng quạt MSI khi mua kèm CPU Ryzen",
      images: [
        "images/mainboard/msi-b650-tomahawk-1.jpg",
        "images/mainboard/msi-b650-tomahawk-2.jpg",
      ],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-09-30",
      thiet_bi_tuong_thich: ["CPU AMD Ryzen 7000-series", "RAM DDR5"],
      tinh_nang: [
        "Wi-Fi 6",
        "Đèn Mystic Light RGB",
        "Tản nhiệt mở rộng",
        "Hỗ trợ PCIe 4.0",
      ],
      danh_muc: "Mainboard",
    },

    {
      id: "mb003",
      ten: "ASUS ROG MAXIMUS Z790 HERO",
      hang: "ASUS",
      gia: 15000000,
      thong_so: {
        chipset: "Z790",
        socket: "LGA 1700",
        formFactor: "ATX",
        memorySlots: 4,
        maxMemory: "128GB",
        pcieSlots: "2 x PCIe 5.0 x16, 1 x PCIe 4.0 x16",
      },
      so_luong: 15,
      mo_ta:
        "Bo mạch chủ cao cấp với VRM 20+1 phase, hỗ trợ DDR5 và PCIe 5.0...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["cao cấp", "ASUS", "ROG", "Z790"],
      rating: 4.9,
      reviewCount: 90,
      khuyen_mai: "Tặng SSD M.2 Gen4",
      images: [
        "images/mainboard/maximus-hero-1.jpg",
        "images/mainboard/maximus-hero-2.jpg",
      ],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-10-20",
      thiet_bi_tuong_thich: ["CPU Intel Gen 12/13", "DDR5"],
      tinh_nang: ["Thunderbolt 4", "WiFi 6E", "PCIe 5.0", "USB 3.2 Gen2x2"],
      danh_muc: "Mainboard",
    },
    {
      id: "mb004",
      ten: "ASRock B650E Steel Legend WiFi",
      hang: "ASRock",
      gia: 7200000,
      thong_so: {
        chipset: "B650E",
        socket: "AM5",
        formFactor: "ATX",
        memorySlots: 4,
        maxMemory: "128GB",
        pcieSlots: "1 x PCIe 5.0 x16, 2 x PCIe 4.0 x16",
      },
      so_luong: 25,
      mo_ta: "Mainboard tầm trung với đầy đủ tính năng cho nền tảng AM5...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["tầm trung", "ASRock", "AM5"],
      rating: 4.6,
      reviewCount: 75,
      khuyen_mai: "Giảm 500.000đ khi mua kèm CPU AMD",
      images: [
        "images/mainboard/asrock-b650e-1.jpg",
        "images/mainboard/asrock-b650e-2.jpg",
      ],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-10-10",
      thiet_bi_tuong_thich: ["CPU AMD Ryzen 7000", "DDR5"],
      tinh_nang: ["2.5GbE LAN", "WiFi 6E", "PCIe 5.0", "USB 3.2 Gen2"],
      danh_muc: "Mainboard",
    },
    {
      id: "mb005",
      ten: "MSI MAG B760 TOMAHAWK WIFI",
      hang: "MSI",
      gia: 5500000,
      thong_so: {
        chipset: "B760",
        socket: "LGA 1700",
        formFactor: "ATX",
        memorySlots: 4,
        maxMemory: "128GB",
        pcieSlots: "1 x PCIe 4.0 x16, 2 x PCIe 3.0 x16",
      },
      so_luong: 30,
      mo_ta:
        "Bo mạch chủ gaming tầm trung với WiFi 6E và thiết kế tản nhiệt hiệu quả...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["gaming", "MSI", "tầm trung"],
      rating: 4.7,
      reviewCount: 120,
      khuyen_mai: "Tặng bộ tản nhiệt M.2",
      images: [
        "images/mainboard/msi-b760-1.jpg",
        "images/mainboard/msi-b760-2.jpg",
      ],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2023-01-05",
      thiet_bi_tuong_thich: ["CPU Intel Gen 12/13", "DDR4/DDR5"],
      tinh_nang: ["2.5G LAN", "WiFi 6E", "USB 3.2 Gen2", "Steel Armor"],
      danh_muc: "Mainboard",
    },
    {
      id: "mb006",
      ten: "Gigabyte X670E AORUS MASTER",
      hang: "Gigabyte",
      gia: 13000000,
      thong_so: {
        chipset: "X670E",
        socket: "AM5",
        formFactor: "E-ATX",
        memorySlots: 4,
        maxMemory: "128GB",
        pcieSlots: "2 x PCIe 5.0 x16",
      },
      so_luong: 20,
      mo_ta: "Bo mạch chủ cao cấp cho nền tảng AM5 với VRM 16+2+2 phase...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["cao cấp", "Gigabyte", "AORUS", "X670E"],
      rating: 4.8,
      reviewCount: 85,
      khuyen_mai: "Tặng tản nhiệt nước AIO",
      images: [
        "images/mainboard/aorus-master-1.jpg",
        "images/mainboard/aorus-master-2.jpg",
      ],
      bao_hanh: "4 năm",
      ngay_phat_hanh: "2022-09-27",
      thiet_bi_tuong_thich: ["CPU AMD Ryzen 7000", "DDR5"],
      tinh_nang: ["10GbE LAN", "WiFi 6E", "PCIe 5.0", "USB4"],
      danh_muc: "Mainboard",
    },
    {
      id: "mb007",
      ten: "ASUS PRIME H610M-K D4",
      hang: "ASUS",
      gia: 2200000,
      thong_so: {
        chipset: "H610",
        socket: "LGA 1700",
        formFactor: "Micro-ATX",
        memorySlots: 2,
        maxMemory: "64GB",
        pcieSlots: "1 x PCIe 4.0 x16",
      },
      so_luong: 40,
      mo_ta: "Bo mạch chủ entry-level giá rẻ cho văn phòng và gaming cơ bản...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["giá rẻ", "ASUS", "văn phòng"],
      rating: 4.4,
      reviewCount: 150,
      khuyen_mai: "Giảm giá khi mua CPU i3",
      images: [
        "images/mainboard/prime-h610-1.jpg",
        "images/mainboard/prime-h610-2.jpg",
      ],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-01-15",
      thiet_bi_tuong_thich: ["CPU Intel Gen 12/13", "DDR4"],
      tinh_nang: ["Realtek LAN", "USB 3.2 Gen1", "M.2 Support"],
      danh_muc: "Mainboard",
    },
    {
      id: "mb008",
      ten: "MSI PRO B650M-A WIFI",
      hang: "MSI",
      gia: 4300000,
      thong_so: {
        chipset: "B650",
        socket: "AM5",
        formFactor: "Micro-ATX",
        memorySlots: 4,
        maxMemory: "128GB",
        pcieSlots: "1 x PCIe 4.0 x16",
      },
      so_luong: 35,
      mo_ta:
        "Bo mạch chủ Micro-ATX phù hợp cho các build nhỏ gọn với AMD Ryzen 7000...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["tầm trung", "MSI", "compact"],
      rating: 4.5,
      reviewCount: 95,
      khuyen_mai: "Tặng kèm tản nhiệt M.2",
      images: [
        "images/mainboard/msi-b650m-1.jpg",
        "images/mainboard/msi-b650m-2.jpg",
      ],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-10-15",
      thiet_bi_tuong_thich: ["CPU AMD Ryzen 7000", "DDR5"],
      tinh_nang: ["2.5G LAN", "WiFi 6E", "PCIe 4.0", "Flash BIOS"],
      danh_muc: "Mainboard",
    },
    {
      id: "mb009",
      ten: "ASRock Z790 PG SONIC",
      hang: "ASRock",
      gia: 8900000,
      thong_so: {
        chipset: "Z790",
        socket: "LGA 1700",
        formFactor: "ATX",
        memorySlots: 4,
        maxMemory: "128GB",
        pcieSlots: "1 x PCIe 5.0 x16, 2 x PCIe 4.0 x16",
      },
      so_luong: 25,
      mo_ta:
        "Bo mạch chủ phiên bản đặc biệt với thiết kế Sonic the Hedgehog...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["gaming", "ASRock", "collector"],
      rating: 4.7,
      reviewCount: 65,
      khuyen_mai: "Tặng figure Sonic",
      images: [
        "images/mainboard/pg-sonic-1.jpg",
        "images/mainboard/pg-sonic-2.jpg",
      ],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-12-20",
      thiet_bi_tuong_thich: ["CPU Intel Gen 12/13", "DDR5"],
      tinh_nang: ["2.5GbE LAN", "WiFi 6E", "PCIe 5.0", "RGB Polychrome"],
      danh_muc: "Mainboard",
    },
    {
      id: "mb010",
      ten: "Gigabyte B650 AORUS ELITE AX",
      hang: "Gigabyte",
      gia: 6500000,
      thong_so: {
        chipset: "B650",
        socket: "AM5",
        formFactor: "ATX",
        memorySlots: 4,
        maxMemory: "128GB",
        pcieSlots: "1 x PCIe 4.0 x16, 2 x PCIe 3.0 x16",
      },
      so_luong: 30,
      mo_ta: "Bo mạch chủ tầm trung với tính năng cao cấp cho platform AM5...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["tầm trung", "Gigabyte", "AORUS"],
      rating: 4.6,
      reviewCount: 110,
      khuyen_mai: "Giảm 400.000đ khi mua kèm CPU AMD",
      images: [
        "images/mainboard/aorus-elite-1.jpg",
        "images/mainboard/aorus-elite-2.jpg",
      ],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-10-10",
      thiet_bi_tuong_thich: ["CPU AMD Ryzen 7000", "DDR5"],
      tinh_nang: ["2.5GbE LAN", "WiFi 6E", "PCIe 4.0", "Q-Flash Plus"],
      danh_muc: "Mainboard",
    },
  ],
  ram: [
    {
      id: "ram001",
      ten: "G.Skill Trident Z5 RGB 32GB",
      hang: "G.Skill",
      gia: 3500000,
      thong_so: {
        capacity: "32GB (2x16GB)",
        speed: "DDR5-6000",
        latency: "CL36",
        voltage: "1.35V",
      },
      so_luong: 25,
      mo_ta:
        "G.Skill Trident Z5 RGB 32GB là bộ RAM DDR5 hiệu năng cao dành cho chơi game và công việc chuyên nghiệp. Với dung lượng 32GB (2x16GB) và tốc độ DDR5-6000, sản phẩm cung cấp băng thông vượt trội cho đa nhiệm, chỉnh sửa video và chơi game nặng. Độ trễ CL36 và điện áp 1.35V đảm bảo ổn định ngay cả khi tải nặng. Tương thích với nền tảng Intel và AMD, RAM hỗ trợ XMP 3.0 để ép xung dễ dàng. Tấm tản nhiệt nhôm và đèn RGB tùy chỉnh qua phần mềm G.Skill hoặc bo mạch chủ nâng cao tính thẩm mỹ. Phù hợp cho PC cao cấp chạy Adobe Photoshop hoặc game như Starfield, bộ RAM này mang lại tốc độ, độ tin cậy và phong cách. Thiết kế thấp đảm bảo tương thích với tản nhiệt CPU lớn, là lựa chọn lý tưởng cho người dùng muốn hiệu năng và vẻ đẹp.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["chơi game", "DDR5", "RGB", "hiệu năng cao"],
      rating: 4.8,
      reviewCount: 150,
      khuyen_mai: "Giảm 10% khi mua 2 bộ",
      images: [
        "images/ram/gskill-trident-z5-1.jpg",
        "images/ram/gskill-trident-z5-2.jpg",
      ],
      bao_hanh: "Bảo hành trọn đời có giới hạn",
      ngay_phat_hanh: "2022-11-01",
      thiet_bi_tuong_thich: ["Bo mạch chủ Intel 600/700-series, AMD AM5"],
      tinh_nang: ["XMP 3.0", "Đèn RGB", "Tản nhiệt nhôm", "DDR5"],
      danh_muc: "RAM",
    },
    {
      id: "ram002",
      ten: "Corsair Vengeance DDR5 32GB",
      hang: "Corsair",
      gia: 3400000,
      thong_so: {
        capacity: "32GB (2x16GB)",
        speed: "DDR5-5600",
        latency: "CL36",
        voltage: "1.25V",
      },
      so_luong: 30,
      mo_ta:
        "Corsair Vengeance DDR5 32GB là bộ RAM hiệu năng cao dành cho game thủ và chuyên gia cần tốc độ cho PC thế hệ mới. Với dung lượng 32GB (2x16GB) và tốc độ DDR5-5600, sản phẩm đáp ứng tốt đa nhiệm, dựng hình 3D và chơi game. Độ trễ CL36 và điện áp 1.25V đảm bảo hiệu quả và ổn định khi xử lý tác vụ nặng. Tương thích với bo mạch chủ Intel 600/700-series và AMD AM5, RAM hỗ trợ XMP 3.0 để ép xung đơn giản. Tấm tản nhiệt thấp cải thiện hiệu suất nhiệt và phù hợp với tản nhiệt CPU lớn. Không có RGB, sản phẩm tập trung vào hiệu năng và thiết kế tối giản, lý tưởng cho hệ thống gọn gàng. Phù hợp với Unreal Engine hoặc game như Call of Duty, bộ RAM này đảm bảo tốc độ và độ bền, khẳng định chất lượng từ Corsair.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["chơi game", "DDR5", "Corsair", "hiệu năng"],
      rating: 4.7,
      reviewCount: 120,
      khuyen_mai: "Tặng miếng lót chuột Corsair khi mua 2 bộ",
      images: [
        "images/ram/corsair-vengeance-ddr5-1.jpg",
        "images/ram/corsair-vengeance-ddr5-2.jpg",
      ],
      bao_hanh: "Bảo hành trọn đời có giới hạn",
      ngay_phat_hanh: "2022-12-15",
      thiet_bi_tuong_thich: ["Bo mạch chủ Intel 600/700-series, AMD AM5"],
      tinh_nang: ["XMP 3.0", "Tản nhiệt thấp", "DDR5"],
      danh_muc: "RAM",
    },
    {
      id: "ram003",
      ten: "Crucial DDR5-4800 32GB",
      hang: "Crucial",
      gia: 2800000,
      thong_so: {
        capacity: "32GB (2x16GB)",
        speed: "DDR5-4800",
        latency: "CL40",
        voltage: "1.1V",
      },
      so_luong: 40,
      mo_ta: "RAM DDR5 giá rẻ phù hợp nâng cấp cho hệ thống DDR5...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["DDR5", "Crucial", "giá rẻ"],
      rating: 4.5,
      reviewCount: 90,
      khuyen_mai: "Giảm giá khi mua 2 bộ",
      images: [
        "images/ram/crucial-ddr5-1.jpg",
        "images/ram/crucial-ddr5-2.jpg",
      ],
      bao_hanh: "Trọn đời",
      ngay_phat_hanh: "2022-06-15",
      thiet_bi_tuong_thich: ["Bo mạch chủ DDR5"],
      tinh_nang: ["On-die ECC", "Điện áp thấp", "DDR5"],
      danh_muc: "RAM",
    },
    {
      id: "ram004",
      ten: "Kingston Fury Beast RGB DDR4",
      hang: "Kingston",
      gia: 1800000,
      thong_so: {
        capacity: "16GB (2x8GB)",
        speed: "DDR4-3600",
        latency: "CL18",
        voltage: "1.35V",
      },
      so_luong: 55,
      mo_ta: "RAM DDR4 với đèn RGB đẹp mắt và hiệu năng ổn định...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["DDR4", "RGB", "Kingston"],
      rating: 4.6,
      reviewCount: 180,
      khuyen_mai: "Tặng đế trưng bày",
      images: [
        "images/ram/kingston-fury-1.jpg",
        "images/ram/kingston-fury-2.jpg",
      ],
      bao_hanh: "Trọn đời",
      ngay_phat_hanh: "2021-08-20",
      thiet_bi_tuong_thich: ["Bo mạch chủ DDR4"],
      tinh_nang: ["RGB Sync", "XMP", "Tản nhiệt nhôm"],
      danh_muc: "RAM",
    },
    {
      id: "ram005",
      ten: "TeamGroup T-Force Delta RGB DDR5",
      hang: "TeamGroup",
      gia: 3200000,
      thong_so: {
        capacity: "32GB (2x16GB)",
        speed: "DDR5-6000",
        latency: "CL38",
        voltage: "1.25V",
      },
      so_luong: 30,
      mo_ta: "RAM DDR5 với thiết kế RGB độc đáo...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["DDR5", "RGB", "TeamGroup"],
      rating: 4.7,
      reviewCount: 85,
      khuyen_mai: "Tặng hub RGB",
      images: [
        "images/ram/teamgroup-delta-1.jpg",
        "images/ram/teamgroup-delta-2.jpg",
      ],
      bao_hanh: "Trọn đời",
      ngay_phat_hanh: "2022-11-15",
      thiet_bi_tuong_thich: ["Bo mạch chủ DDR5"],
      tinh_nang: ["RGB", "XMP 3.0", "Tản nhiệt cao cấp"],
      danh_muc: "RAM",
    },
    {
      id: "ram006",
      ten: "Corsair Dominator Platinum RGB DDR5",
      hang: "Corsair",
      gia: 4500000,
      thong_so: {
        capacity: "32GB (2x16GB)",
        speed: "DDR5-6400",
        latency: "CL32",
        voltage: "1.35V",
      },
      so_luong: 25,
      mo_ta: "RAM DDR5 cao cấp với thiết kế độc quyền Dominator...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["DDR5", "RGB", "Corsair", "cao cấp"],
      rating: 4.9,
      reviewCount: 120,
      khuyen_mai: "Tặng iCUE Controller",
      images: [
        "images/ram/corsair-dominator-1.jpg",
        "images/ram/corsair-dominator-2.jpg",
      ],
      bao_hanh: "Trọn đời",
      ngay_phat_hanh: "2022-12-01",
      thiet_bi_tuong_thich: ["Bo mạch chủ DDR5"],
      tinh_nang: ["Capellix RGB", "iCUE", "DHX Cooling"],
      danh_muc: "RAM",
    },
    {
      id: "ram007",
      ten: "G.Skill Ripjaws V DDR4",
      hang: "G.Skill",
      gia: 1500000,
      thong_so: {
        capacity: "16GB (2x8GB)",
        speed: "DDR4-3200",
        latency: "CL16",
        voltage: "1.35V",
      },
      so_luong: 60,
      mo_ta: "RAM DDR4 giá rẻ hiệu năng tốt...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["DDR4", "G.Skill", "giá rẻ"],
      rating: 4.5,
      reviewCount: 250,
      khuyen_mai: "Giảm giá khi mua số lượng",
      images: [
        "images/ram/gskill-ripjaws-1.jpg",
        "images/ram/gskill-ripjaws-2.jpg",
      ],
      bao_hanh: "Trọn đời",
      ngay_phat_hanh: "2020-06-15",
      thiet_bi_tuong_thich: ["Bo mạch chủ DDR4"],
      tinh_nang: ["XMP", "Tản nhiệt nhôm", "Độ tin cậy cao"],
      danh_muc: "RAM",
    },
    {
      id: "ram008",
      ten: "ADATA XPG Lancer RGB DDR5",
      hang: "ADATA",
      gia: 3800000,
      thong_so: {
        capacity: "32GB (2x16GB)",
        speed: "DDR5-6000",
        latency: "CL36",
        voltage: "1.35V",
      },
      so_luong: 35,
      mo_ta: "RAM DDR5 hiệu năng cao với RGB độc đáo...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["DDR5", "RGB", "ADATA"],
      rating: 4.6,
      reviewCount: 75,
      khuyen_mai: "Tặng strip LED RGB",
      images: [
        "images/ram/adata-lancer-1.jpg",
        "images/ram/adata-lancer-2.jpg",
      ],
      bao_hanh: "Trọn đời",
      ngay_phat_hanh: "2022-09-20",
      thiet_bi_tuong_thich: ["Bo mạch chủ DDR5"],
      tinh_nang: ["RGB Sync", "XMP 3.0", "Tản nhiệt cao cấp"],
      danh_muc: "RAM",
    },
    {
      id: "ram009",
      ten: "Thermaltake TOUGHRAM RGB DDR4",
      hang: "Thermaltake",
      gia: 2200000,
      thong_so: {
        capacity: "16GB (2x8GB)",
        speed: "DDR4-4000",
        latency: "CL18",
        voltage: "1.35V",
      },
      so_luong: 40,
      mo_ta: "RAM DDR4 tốc độ cao với RGB 16.8 triệu màu...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["DDR4", "RGB", "Thermaltake"],
      rating: 4.5,
      reviewCount: 95,
      khuyen_mai: "Tặng phần mềm điều khiển RGB",
      images: [
        "images/ram/thermaltake-toughram-1.jpg",
        "images/ram/thermaltake-toughram-2.jpg",
      ],
      bao_hanh: "Trọn đời",
      ngay_phat_hanh: "2021-12-10",
      thiet_bi_tuong_thich: ["Bo mạch chủ DDR4"],
      tinh_nang: ["RGB", "XMP 2.0", "Tản nhiệt 10 lớp"],
      danh_muc: "RAM",
    },
    {
      id: "ram010",
      ten: "Patriot Viper Steel DDR4",
      hang: "Patriot",
      gia: 1600000,
      thong_so: {
        capacity: "16GB (2x8GB)",
        speed: "DDR4-3600",
        latency: "CL17",
        voltage: "1.35V",
      },
      so_luong: 45,
      mo_ta: "RAM DDR4 hiệu năng cao giá tốt...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["DDR4", "Patriot", "giá rẻ"],
      rating: 4.4,
      reviewCount: 140,
      khuyen_mai: "Giảm 10% khi mua cùng mainboard",
      images: [
        "images/ram/patriot-viper-1.jpg",
        "images/ram/patriot-viper-2.jpg",
      ],
      bao_hanh: "Trọn đời",
      ngay_phat_hanh: "2021-03-15",
      thiet_bi_tuong_thich: ["Bo mạch chủ DDR4"],
      tinh_nang: ["XMP 2.0", "Tản nhiệt nhôm", "Ép xung tốt"],
      danh_muc: "RAM",
    },
  ],
  storage: [
    {
      id: "ssd001",
      ten: "Samsung 990 Pro 1TB",
      hang: "Samsung",
      gia: 2000000,
      thong_so: {
        type: "NVMe SSD",
        capacity: "1TB",
        readSpeed: "7450 MB/s",
        writeSpeed: "6900 MB/s",
        interface: "PCIe 4.0",
      },
      so_luong: 69,
      mo_ta:
        "Samsung 990 Pro 1TB là ổ cứng NVMe SSD cao cấp dành cho game thủ, nhà sáng tạo và chuyên gia. Với tốc độ đọc 7450 MB/s và ghi 6900 MB/s, ổ cứng mang lại hiệu năng vượt trội khi tải game, chỉnh sửa video 4K và truyền dữ liệu lớn. Giao thức PCIe 4.0 đảm bảo tương thích với bo mạch chủ hiện đại, trong khi dung lượng 1TB đủ cho game, media và phần mềm. Công nghệ V-NAND của Samsung và bộ điều khiển mạnh mẽ cung cấp độ bền cao (lên đến 1200 TBW) và độ tin cậy tuyệt đối. Phần mềm Samsung Magician tối ưu hiệu suất và theo dõi tình trạng ổ. Phù hợp cho PC hiệu năng cao, ổ cứng này giảm thời gian khởi động và tăng hiệu quả công việc, lý tưởng cho Adobe Premiere hoặc game như Elden Ring, được đảm bảo bởi chất lượng Samsung.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["SSD", "Samsung", "NVMe", "tốc độ cao"],
      rating: 4.9,
      reviewCount: 400,
      khuyen_mai: "Tặng cáp PCIe Gen4 khi mua 2 chiếc",
      images: [
        "images/storage/samsung-990-pro-1.jpg",
        "images/storage/samsung-990-pro-2.jpg",
      ],
      bao_hanh: "5 năm",
      ngay_phat_hanh: "2022-10-25",
      thiet_bi_tuong_thich: ["Bo mạch chủ PCIe 4.0", "PS5 (kèm tản nhiệt)"],
      tinh_nang: [
        "Công nghệ V-NAND",
        "Phần mềm Samsung Magician",
        "PCIe 4.0",
        "Độ bền cao",
      ],
      danh_muc: "Storage",
    },
    {
      id: "ssd002",
      ten: "WD Black SN850X 2TB",
      hang: "Western Digital",
      gia: 4500000,
      thong_so: {
        type: "NVMe SSD",
        capacity: "2TB",
        readSpeed: "7300 MB/s",
        writeSpeed: "6600 MB/s",
        interface: "PCIe 4.0",
      },
      so_luong: 40,
      mo_ta:
        "WD Black SN850X 2TB là ổ cứng NVMe SSD hiệu năng cao tối ưu cho chơi game và công việc chuyên nghiệp. Với tốc độ đọc 7300 MB/s và ghi 6600 MB/s, ổ cứng đảm bảo tải game nhanh, truyền dữ liệu tức thời và khởi động hệ thống siêu tốc. Dung lượng 2TB chứa được thư viện game lớn, dự án video 4K và phần mềm sáng tạo. Giao thức PCIe 4.0 tương thích với PC hiện đại và PS5 (kèm tản nhiệt). Chế độ Game Mode 2.0 của WD tăng hiệu năng khi chơi game nặng, trong khi phần mềm WD Dashboard theo dõi và tối ưu ổ cứng. Với độ bền lên đến 1200 TBW, sản phẩm đảm bảo tuổi thọ cao. Lý tưởng cho người dùng dựng PC cao cấp hoặc sáng tạo với DaVinci Resolve, SN850X mang lại tốc độ, dung lượng và độ tin cậy vượt trội.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["SSD", "WD", "NVMe", "chơi game"],
      rating: 4.8,
      reviewCount: 250,
      khuyen_mai: "Tặng tản nhiệt khi mua cho PS5",
      images: [
        "images/storage/wd-sn850x-1.jpg",
        "images/storage/wd-sn850x-2.jpg",
      ],
      bao_hanh: "5 năm",
      ngay_phat_hanh: "2022-08-10",
      thiet_bi_tuong_thich: ["Bo mạch chủ PCIe 4.0", "PS5"],
      tinh_nang: [
        "Chế độ Game Mode 2.0",
        "Phần mềm WD Dashboard",
        "PCIe 4.0",
        "Độ bền cao",
      ],
      danh_muc: "Storage",
    },

    {
      id: "storage003",
      ten: "Seagate BarraCuda 4TB",
      hang: "Seagate",
      gia: 2800000,
      thong_so: {
        type: "HDD",
        capacity: "4TB",
        readSpeed: "190 MB/s",
        writeSpeed: "180 MB/s",
        interface: "SATA 6Gb/s",
        rpm: "5400 RPM",
      },
      so_luong: 50,
      mo_ta:
        "Ổ cứng HDD dung lượng lớn cho lưu trữ, thích hợp cho game thủ và người dùng cần nhiều không gian...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["HDD", "Seagate", "lưu trữ"],
      rating: 4.5,
      reviewCount: 320,
      khuyen_mai: "Giảm 15% khi mua từ 2 ổ",
      images: [
        "images/storage/seagate-4tb-1.jpg",
        "images/storage/seagate-4tb-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2021-06-15",
      thiet_bi_tuong_thich: ["PC", "NAS"],
      tinh_nang: ["CMR", "Multi-tier caching", "NAS ready"],
      danh_muc: "Storage",
    },
    {
      id: "storage004",
      ten: "Crucial P3 Plus 2TB",
      hang: "Crucial",
      gia: 3500000,
      thong_so: {
        type: "NVMe SSD",
        capacity: "2TB",
        readSpeed: "5000 MB/s",
        writeSpeed: "4200 MB/s",
        interface: "PCIe 4.0",
        form_factor: "M.2 2280",
      },
      so_luong: 35,
      mo_ta: "SSD NVMe giá rẻ với hiệu năng tốt cho gaming và công việc...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["SSD", "NVMe", "Crucial", "giá rẻ"],
      rating: 4.6,
      reviewCount: 180,
      khuyen_mai: "Tặng tản nhiệt M.2",
      images: [
        "images/storage/crucial-p3-1.jpg",
        "images/storage/crucial-p3-2.jpg",
      ],
      bao_hanh: "5 năm",
      ngay_phat_hanh: "2022-08-20",
      thiet_bi_tuong_thich: ["Bo mạch chủ PCIe 4.0"],
      tinh_nang: ["NVMe", "Crucial Storage Executive", "PCIe 4.0"],
      danh_muc: "Storage",
    },
    {
      id: "storage005",
      ten: "WD Red Pro 14TB",
      hang: "Western Digital",
      gia: 12000000,
      thong_so: {
        type: "HDD",
        capacity: "14TB",
        readSpeed: "255 MB/s",
        writeSpeed: "240 MB/s",
        interface: "SATA 6Gb/s",
        rpm: "7200 RPM",
      },
      so_luong: 15,
      mo_ta: "HDD cao cấp cho NAS và máy chủ, độ tin cậy cao...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["HDD", "WD", "NAS", "Server"],
      rating: 4.8,
      reviewCount: 95,
      khuyen_mai: "Tặng UPS khi mua 2 ổ",
      images: [
        "images/storage/wd-red-pro-1.jpg",
        "images/storage/wd-red-pro-2.jpg",
      ],
      bao_hanh: "5 năm",
      ngay_phat_hanh: "2022-03-10",
      thiet_bi_tuong_thich: ["NAS", "Server"],
      tinh_nang: [
        "NASware 3.0",
        "3D Active Balance Plus",
        "Multi-axis shock sensor",
      ],
      danh_muc: "Storage",
    },
    {
      id: "storage006",
      ten: "Corsair MP600 PRO XT 2TB",
      hang: "Corsair",
      gia: 6500000,
      thong_so: {
        type: "NVMe SSD",
        capacity: "2TB",
        readSpeed: "7100 MB/s",
        writeSpeed: "6800 MB/s",
        interface: "PCIe 4.0",
        form_factor: "M.2 2280",
      },
      so_luong: 25,
      mo_ta: "SSD NVMe cao cấp với tản nhiệt tích hợp...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["SSD", "NVMe", "Corsair", "cao cấp"],
      rating: 4.9,
      reviewCount: 150,
      khuyen_mai: "Giảm 500.000đ khi mua kèm mainboard",
      images: [
        "images/storage/corsair-mp600-1.jpg",
        "images/storage/corsair-mp600-2.jpg",
      ],
      bao_hanh: "5 năm",
      ngay_phat_hanh: "2022-09-15",
      thiet_bi_tuong_thich: ["Bo mạch chủ PCIe 4.0"],
      tinh_nang: ["Tản nhiệt nhôm", "Phần mềm SSD Toolbox", "3D TLC NAND"],
      danh_muc: "Storage",
    },
    {
      id: "storage007",
      ten: "Samsung 870 EVO 2TB",
      hang: "Samsung",
      gia: 4800000,
      thong_so: {
        type: "SATA SSD",
        capacity: "2TB",
        readSpeed: "560 MB/s",
        writeSpeed: "530 MB/s",
        interface: "SATA III",
        form_factor: "2.5 inch",
      },
      so_luong: 40,
      mo_ta: "SSD SATA độ tin cậy cao cho upgrade laptop và PC...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["SSD", "SATA", "Samsung"],
      rating: 4.7,
      reviewCount: 280,
      khuyen_mai: "Tặng cáp SATA",
      images: [
        "images/storage/samsung-870-1.jpg",
        "images/storage/samsung-870-2.jpg",
      ],
      bao_hanh: "5 năm",
      ngay_phat_hanh: "2021-01-20",
      thiet_bi_tuong_thich: ["PC", "Laptop"],
      tinh_nang: ["Samsung Magician", "V-NAND", "AES 256-bit encryption"],
      danh_muc: "Storage",
    },
    {
      id: "storage008",
      ten: "Seagate FireCuda 530 1TB",
      hang: "Seagate",
      gia: 5500000,
      thong_so: {
        type: "NVMe SSD",
        capacity: "1TB",
        readSpeed: "7300 MB/s",
        writeSpeed: "6900 MB/s",
        interface: "PCIe 4.0",
        form_factor: "M.2 2280",
      },
      so_luong: 30,
      mo_ta: "SSD NVMe cao cấp tương thích PS5...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["SSD", "NVMe", "Seagate", "PS5"],
      rating: 4.8,
      reviewCount: 140,
      khuyen_mai: "Tặng tản nhiệt Heatsink",
      images: [
        "images/storage/firecuda-530-1.jpg",
        "images/storage/firecuda-530-2.jpg",
      ],
      bao_hanh: "5 năm",
      ngay_phat_hanh: "2021-08-31",
      thiet_bi_tuong_thich: ["PC", "PS5"],
      tinh_nang: ["3D TLC NAND", "Seagate SeaTools", "GameDrive"],
      danh_muc: "Storage",
    },
    {
      id: "storage009",
      ten: "Western Digital Blue 4TB",
      hang: "Western Digital",
      gia: 2500000,
      thong_so: {
        type: "HDD",
        capacity: "4TB",
        readSpeed: "180 MB/s",
        writeSpeed: "175 MB/s",
        interface: "SATA 6Gb/s",
        rpm: "5400 RPM",
      },
      so_luong: 55,
      mo_ta: "HDD tin cậy cho người dùng phổ thông...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["HDD", "WD", "lưu trữ"],
      rating: 4.5,
      reviewCount: 220,
      khuyen_mai: "Giảm giá khi mua số lượng",
      images: ["images/storage/wd-blue-1.jpg", "images/storage/wd-blue-2.jpg"],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2021-05-15",
      thiet_bi_tuong_thich: ["PC", "Laptop"],
      tinh_nang: ["NoTouch ramp load", "IntelliSeek", "Data LifeGuard"],
      danh_muc: "Storage",
    },
    {
      id: "storage010",
      ten: "ADATA Legend 960 2TB",
      hang: "ADATA",
      gia: 4200000,
      thong_so: {
        type: "NVMe SSD",
        capacity: "2TB",
        readSpeed: "7400 MB/s",
        writeSpeed: "6800 MB/s",
        interface: "PCIe 4.0",
        form_factor: "M.2 2280",
      },
      so_luong: 35,
      mo_ta: "SSD NVMe hiệu năng cao với giá cả phải chăng...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["SSD", "NVMe", "ADATA"],
      rating: 4.6,
      reviewCount: 85,
      khuyen_mai: "Tặng phần mềm Acronis True Image",
      images: [
        "images/storage/adata-legend-1.jpg",
        "images/storage/adata-legend-2.jpg",
      ],
      bao_hanh: "5 năm",
      ngay_phat_hanh: "2022-11-10",
      thiet_bi_tuong_thich: ["Bo mạch chủ PCIe 4.0"],
      tinh_nang: ["LDPC ECC", "SLC Caching", "RAID Engine"],
      danh_muc: "Storage",
    },
  ],
  gpu: [
    {
      id: "gpu001",
      ten: "NVIDIA GeForce RTX 4090",
      hang: "NVIDIA",
      gia: 40000000,
      thong_so: {
        vram: "24GB GDDR6X",
        cudaCores: 16384,
        boostClock: "2.52 GHz",
        power: "450W",
      },
      so_luong: 10,
      mo_ta:
        "NVIDIA GeForce RTX 4090 là card đồ họa đỉnh cao cho game thủ và chuyên gia cần hiệu năng 4K và 8K. Với 24GB bộ nhớ GDDR6X và 16384 nhân CUDA, sản phẩm mang lại sức mạnh vượt trội cho chơi game có hiệu ứng ray tracing, công việc AI và dựng hình 3D. Tốc độ tăng tốc 2.52 GHz đảm bảo chơi mượt các tựa game như Starfield và Cyberpunk 2077 ở cài đặt tối đa. Công nghệ DLSS 3 và ray tracing tạo hình ảnh chân thực, tăng FPS đáng kể. Kiến trúc Ada Lovelace cải thiện hiệu suất năng lượng, trong khi mã hóa AV1 hỗ trợ streamer và nhà sáng tạo. Phù hợp cho PC chơi game cao cấp hoặc máy trạm chạy Blender, RTX 4090 hỗ trợ HDMI 2.1 và DisplayPort 1.4. Hệ thống tản nhiệt cao cấp và chất lượng build đảm bảo độ bền, là lựa chọn hàng đầu cho hiệu năng tối ưu.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["RTX", "cao cấp", "chơi game 4K", "ray tracing"],
      rating: 5.0,
      reviewCount: 180,
      khuyen_mai: "Tặng lót chuột RTX khi mua kèm PSU 1000W",
      images: ["images/gpu/rtx-4090-1.jpg", "images/gpu/rtx-4090-2.jpg"],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-10-12",
      thiet_bi_tuong_thich: ["Bo mạch chủ PCIe 4.0", "Nguồn 850W trở lên"],
      tinh_nang: [
        "DLSS 3",
        "Ray Tracing",
        "Mã hóa AV1",
        "Kiến trúc Ada Lovelace",
      ],
      danh_muc: "GPU",
    },
    {
      id: "gpu002",
      ten: "AMD Radeon RX 7900 XTX",
      hang: "AMD",
      gia: 25000000,
      thong_so: {
        vram: "24GB GDDR6",
        streamProcessors: 6144,
        boostClock: "2.5 GHz",
        power: "355W",
      },
      so_luong: 15,
      mo_ta:
        "AMD Radeon RX 7900 XTX là card đồ họa mạnh mẽ dành cho chơi game 4K và công việc sáng tạo, sử dụng kiến trúc RDNA 3 tiên tiến. Với 24GB bộ nhớ GDDR6 và 6144 nhân xử lý, sản phẩm mang lại hiệu năng ấn tượng cho game như Assassin’s Creed Valhalla và phần mềm như Adobe After Effects. Tốc độ tăng tốc 2.5 GHz cùng công nghệ FSR 3 đảm bảo hình ảnh mượt mà và chất lượng cao. Hỗ trợ DisplayPort 2.1 và HDMI 2.1, card này lý tưởng cho màn hình tần số quét cao. Với công suất 355W, sản phẩm tiết kiệm năng lượng hơn so với đối thủ. RX 7900 XTX hỗ trợ ray tracing và driver tối ưu cho cả game thủ và nhà sáng tạo. Thiết kế tản nhiệt tiên tiến giữ nhiệt độ thấp, là lựa chọn hấp dẫn cho người dùng muốn hiệu năng cao với giá trị tốt.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["Radeon", "chơi game 4K", "RDNA3", "ray tracing"],
      rating: 4.8,
      reviewCount: 160,
      khuyen_mai: "Tặng game AMD khi mua trước 31/05/2025",
      images: ["images/gpu/rx-7900-xtx-1.jpg", "images/gpu/rx-7900-xtx-2.jpg"],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-12-13",
      thiet_bi_tuong_thich: ["Bo mạch chủ PCIe 4.0", "Nguồn 750W trở lên"],
      tinh_nang: [
        "FSR 3",
        "Kiến trúc RDNA 3",
        "DisplayPort 2.1",
        "Ray Tracing",
      ],
      danh_muc: "GPU",
    },
    {
      id: "gpu003",
      ten: "ASUS ROG STRIX RTX 4080 OC",
      hang: "ASUS",
      gia: 32000000,
      thong_so: {
        vram: "16GB GDDR6X",
        cudaCores: 9728,
        boostClock: "2.61 GHz",
        power: "320W",
        interface: "PCIe 4.0",
        ports: "3x DisplayPort 1.4a, 1x HDMI 2.1",
      },
      so_luong: 20,
      mo_ta:
        "Card đồ họa cao cấp với thiết kế tản nhiệt ROG được tối ưu và RGB Aura Sync...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["RTX 4080", "ASUS", "ROG", "gaming"],
      rating: 4.8,
      reviewCount: 145,
      khuyen_mai: "Tặng kèm support bracket",
      images: ["images/gpu/asus-4080-1.jpg", "images/gpu/asus-4080-2.jpg"],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-11-16",
      thiet_bi_tuong_thich: ["PSU 750W+"],
      tinh_nang: ["DLSS 3", "Ray Tracing", "0dB Technology", "GPU Tweak III"],
      danh_muc: "GPU",
    },
    {
      id: "gpu004",
      ten: "MSI RX 7800 XT GAMING X TRIO",
      hang: "MSI",
      gia: 17500000,
      thong_so: {
        vram: "16GB GDDR6",
        streamProcessors: 3840,
        boostClock: "2.43 GHz",
        power: "263W",
        interface: "PCIe 4.0",
        ports: "2x DisplayPort 2.1, 2x HDMI 2.1",
      },
      so_luong: 30,
      mo_ta:
        "Card đồ họa tầm trung-cao cấp với hiệu năng mạnh mẽ cho gaming 1440p và 4K...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["RX 7800 XT", "MSI", "gaming"],
      rating: 4.7,
      reviewCount: 120,
      khuyen_mai: "Tặng game AMD bundle",
      images: ["images/gpu/msi-7800xt-1.jpg", "images/gpu/msi-7800xt-2.jpg"],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2023-09-06",
      thiet_bi_tuong_thich: ["PSU 650W+"],
      tinh_nang: ["FSR 3", "Mystic Light", "Zero Frozr", "AMD RDNA 3"],
      danh_muc: "GPU",
    },
    {
      id: "gpu005",
      ten: "Gigabyte RTX 4070 GAMING OC",
      hang: "Gigabyte",
      gia: 15500000,
      thong_so: {
        vram: "12GB GDDR6X",
        cudaCores: 5888,
        boostClock: "2.58 GHz",
        power: "200W",
        interface: "PCIe 4.0",
        ports: "3x DisplayPort 1.4a, 1x HDMI 2.1",
      },
      so_luong: 40,
      mo_ta: "Card đồ họa tầm trung hiệu năng cao với thiết kế 3 quạt...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["RTX 4070", "Gigabyte", "gaming"],
      rating: 4.6,
      reviewCount: 180,
      khuyen_mai: "Giảm 500.000đ khi mua kèm PSU",
      images: [
        "images/gpu/gigabyte-4070-1.jpg",
        "images/gpu/gigabyte-4070-2.jpg",
      ],
      bao_hanh: "4 năm",
      ngay_phat_hanh: "2023-04-13",
      thiet_bi_tuong_thich: ["PSU 650W+"],
      tinh_nang: ["DLSS 3", "Ray Tracing", "RGB Fusion 2.0", "Windforce 3X"],
      danh_muc: "GPU",
    },
    {
      id: "gpu006",
      ten: "Sapphire NITRO+ RX 7900 XT",
      hang: "Sapphire",
      gia: 23000000,
      thong_so: {
        vram: "20GB GDDR6",
        streamProcessors: 5376,
        boostClock: "2.5 GHz",
        power: "300W",
        interface: "PCIe 4.0",
        ports: "2x DisplayPort 2.1, 2x HDMI 2.1",
      },
      so_luong: 25,
      mo_ta: "Card đồ họa cao cấp với thiết kế NITRO+ độc quyền...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["RX 7900 XT", "Sapphire", "NITRO+"],
      rating: 4.8,
      reviewCount: 95,
      khuyen_mai: "Tặng Wallpaper Engine",
      images: [
        "images/gpu/sapphire-7900xt-1.jpg",
        "images/gpu/sapphire-7900xt-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2022-12-13",
      thiet_bi_tuong_thich: ["PSU 750W+"],
      tinh_nang: ["FSR 3", "ARGB", "Tri-X Cooling", "Hybrid Fan Control"],
      danh_muc: "GPU",
    },
    {
      id: "gpu007",
      ten: "ZOTAC RTX 4060 Ti Twin Edge",
      hang: "ZOTAC",
      gia: 11000000,
      thong_so: {
        vram: "8GB GDDR6",
        cudaCores: 4352,
        boostClock: "2.54 GHz",
        power: "160W",
        interface: "PCIe 4.0",
        ports: "3x DisplayPort 1.4a, 1x HDMI 2.1",
      },
      so_luong: 45,
      mo_ta: "Card đồ họa compact hiệu năng tốt cho gaming 1440p...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["RTX 4060 Ti", "ZOTAC", "compact"],
      rating: 4.5,
      reviewCount: 150,
      khuyen_mai: "Tặng Steam Wallet 200.000đ",
      images: [
        "images/gpu/zotac-4060ti-1.jpg",
        "images/gpu/zotac-4060ti-2.jpg",
      ],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2023-05-24",
      thiet_bi_tuong_thich: ["PSU 550W+"],
      tinh_nang: ["DLSS 3", "Ray Tracing", "IceStorm 2.0", "FireStorm"],
      danh_muc: "GPU",
    },
    {
      id: "gpu008",
      ten: "PowerColor RX 7600 Fighter",
      hang: "PowerColor",
      gia: 8000000,
      thong_so: {
        vram: "8GB GDDR6",
        streamProcessors: 2048,
        boostClock: "2.47 GHz",
        power: "165W",
        interface: "PCIe 4.0",
        ports: "2x DisplayPort 1.4, 2x HDMI 2.1",
      },
      so_luong: 55,
      mo_ta:
        "Card đồ họa tầm trung giá rẻ với hiệu năng tốt cho gaming 1080p...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["RX 7600", "PowerColor", "giá rẻ"],
      rating: 4.4,
      reviewCount: 85,
      khuyen_mai: "Giảm 300.000đ khi mua kèm main AMD",
      images: [
        "images/gpu/powercolor-7600-1.jpg",
        "images/gpu/powercolor-7600-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2023-05-24",
      thiet_bi_tuong_thich: ["PSU 500W+"],
      tinh_nang: ["FSR 3", "Dual Fan", "Dr.MOS", "Mute Fan"],
      danh_muc: "GPU",
    },
    {
      id: "gpu009",
      ten: "ASUS TUF RTX 4070 Ti GAMING",
      hang: "ASUS",
      gia: 21000000,
      thong_so: {
        vram: "12GB GDDR6X",
        cudaCores: 7680,
        boostClock: "2.73 GHz",
        power: "285W",
        interface: "PCIe 4.0",
        ports: "3x DisplayPort 1.4a, 1x HDMI 2.1",
      },
      so_luong: 35,
      mo_ta: "Card đồ họa cao cấp với thiết kế TUF Gaming bền bỉ...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["RTX 4070 Ti", "ASUS", "TUF"],
      rating: 4.7,
      reviewCount: 130,
      khuyen_mai: "Tặng gaming chair TUF",
      images: [
        "images/gpu/asus-tuf-4070ti-1.jpg",
        "images/gpu/asus-tuf-4070ti-2.jpg",
      ],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2023-01-05",
      thiet_bi_tuong_thich: ["PSU 750W+"],
      tinh_nang: ["DLSS 3", "Ray Tracing", "Military Grade", "Dual BIOS"],
      danh_muc: "GPU",
    },
    {
      id: "gpu010",
      ten: "MSI RX 6650 XT GAMING X",
      hang: "MSI",
      gia: 7500000,
      thong_so: {
        vram: "8GB GDDR6",
        streamProcessors: 2048,
        boostClock: "2.69 GHz",
        power: "180W",
        interface: "PCIe 4.0",
        ports: "2x DisplayPort 1.4, 2x HDMI 2.1",
      },
      so_luong: 50,
      mo_ta: "Card đồ họa tầm trung giá tốt với thiết kế Gaming X đẹp mắt...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["RX 6650 XT", "MSI", "gaming"],
      rating: 4.5,
      reviewCount: 170,
      khuyen_mai: "Tặng bàn di chuột MSI",
      images: ["images/gpu/msi-6650xt-1.jpg", "images/gpu/msi-6650xt-2.jpg"],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-05-10",
      thiet_bi_tuong_thich: ["PSU 500W+"],
      tinh_nang: ["FSR", "Mystic Light", "TORX Fan 4.0", "Zero Frozr"],
      danh_muc: "GPU",
    },
  ],
  psu: [
    {
      id: "psu001",
      ten: "Corsair RM850x",
      hang: "Corsair",
      gia: 3750000,
      thong_so: {
        wattage: "850W",
        efficiency: "80+ Gold",
        modular: "Fully Modular",
        connectors: "ATX 24-pin, EPS 8-pin",
      },
      so_luong: 40,
      mo_ta:
        "Corsair RM850x là nguồn máy tính 850W hiệu năng cao dành cho PC chơi game và máy trạm. Với chứng nhận 80+ Gold, nguồn giảm thiểu lãng phí năng lượng và tỏa nhiệt, đảm bảo cấp điện ổn định cho linh kiện cao cấp như RTX 4090 hoặc CPU Ryzen 9. Thiết kế hoàn toàn mô-đun giúp quản lý cáp gọn gàng, cải thiện luồng khí và thẩm mỹ. Quạt 135mm từ tính hoạt động êm ái ngay cả khi tải nặng. Nguồn sử dụng tụ điện cao cấp cho điện áp ổn định và hỗ trợ chuẩn ATX 3.0, tương thích với GPU hiện đại cần đầu nối 12VHPWR. Phù hợp cho người dùng lắp ráp hệ thống mạnh mẽ, RM850x mang lại độ bền, hiệu suất và linh hoạt, được Corsair đảm bảo với bảo hành 10 năm, mang lại sự an tâm tuyệt đối.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["nguồn", "Corsair", "mô-đun", "hiệu suất cao"],
      rating: 4.7,
      reviewCount: 130,
      khuyen_mai: "Giảm 5% khi mua cùng RTX 4090",
      images: [
        "images/psu/corsair-rm850x-1.jpg",
        "images/psu/corsair-rm850x-2.jpg",
      ],
      bao_hanh: "10 năm",
      ngay_phat_hanh: "2021-08-10",
      thiet_bi_tuong_thich: ["Bo mạch chủ ATX", "GPU cao cấp"],
      tinh_nang: [
        "80+ Gold",
        "Hoàn toàn mô-đun",
        "Quạt từ tính",
        "Hỗ trợ ATX 3.0",
      ],
      danh_muc: "PSU",
    },
    {
      id: "psu002",
      ten: "Seasonic Prime TX-1000",
      hang: "Seasonic",
      gia: 6500000,
      thong_so: {
        wattage: "1000W",
        efficiency: "80+ Titanium",
        modular: "Fully Modular",
        connectors: "ATX 24-pin, EPS 8-pin, 12VHPWR",
      },
      so_luong: 20,
      mo_ta:
        "Seasonic Prime TX-1000 là nguồn máy tính 1000W cao cấp dành cho PC hiệu năng cao và máy trạm chuyên nghiệp. Chứng nhận 80+ Titanium đảm bảo hiệu suất năng lượng tối đa, giảm nhiệt và chi phí điện. Thiết kế hoàn toàn mô-đun hỗ trợ quản lý cáp gọn gàng, phù hợp với GPU như RTX 4090 và CPU như i9-13900K. Quạt 135mm với ổ bi động lực học hoạt động gần như không tiếng ồn, ngay cả khi tải nặng. Hỗ trợ chuẩn ATX 3.0 và đầu nối 12VHPWR, nguồn sẵn sàng cho linh kiện thế hệ mới. Tụ điện cao cấp và thiết kế bền bỉ đảm bảo cấp điện ổn định và tuổi thọ lâu dài. Phù hợp cho người dùng chuyên sâu hoặc hệ thống đa GPU, TX-1000 kết hợp công nghệ tiên tiến và chất lượng vượt trội của Seasonic, được bảo hành 12 năm để đảm bảo sự an tâm.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["nguồn", "Seasonic", "mô-đun", "Titanium"],
      rating: 4.9,
      reviewCount: 100,
      khuyen_mai: "Tặng cáp nối dài Seasonic khi mua",
      images: [
        "images/psu/seasonic-tx1000-1.jpg",
        "images/psu/seasonic-tx1000-2.jpg",
      ],
      bao_hanh: "12 năm",
      ngay_phat_hanh: "2022-06-15",
      thiet_bi_tuong_thich: ["Bo mạch chủ ATX", "GPU thế hệ mới"],
      tinh_nang: [
        "80+ Titanium",
        "Hoàn toàn mô-đun",
        "Quạt ổ bi động lực",
        "Hỗ trợ ATX 3.0",
      ],
      danh_muc: "PSU",
    },

    {
      id: "psu003",
      ten: "be quiet! Dark Power Pro 12 1500W",
      hang: "be quiet!",
      gia: 12000000,
      thong_so: {
        wattage: "1500W",
        efficiency: "80+ Titanium",
        modular: "Fully Modular",
        connectors: "ATX 24-pin, 2x EPS 8-pin, 6x PCIe 8-pin",
      },
      so_luong: 15,
      mo_ta: "Nguồn cao cấp cho workstation và mining với hiệu suất tối đa...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["PSU", "be quiet!", "cao cấp", "workstation"],
      rating: 4.9,
      reviewCount: 75,
      khuyen_mai: "Tặng bộ cáp sleeved custom",
      images: [
        "images/psu/bequiet-1500w-1.jpg",
        "images/psu/bequiet-1500w-2.jpg",
      ],
      bao_hanh: "10 năm",
      ngay_phat_hanh: "2022-03-15",
      thiet_bi_tuong_thich: ["ATX 3.0", "PCIe 5.0"],
      tinh_nang: [
        "Silent Wings",
        "Titanium Efficiency",
        "OC Key",
        "Digital Interface",
      ],
      danh_muc: "PSU",
    },
    {
      id: "psu004",
      ten: "ASUS ROG THOR 1000W Platinum II",
      hang: "ASUS",
      gia: 8500000,
      thong_so: {
        wattage: "1000W",
        efficiency: "80+ Platinum",
        modular: "Fully Modular",
        connectors: "ATX 24-pin, 2x EPS, 5x PCIe",
      },
      so_luong: 25,
      mo_ta: "Nguồn gaming cao cấp với màn hình OLED và RGB...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["PSU", "ASUS", "ROG", "RGB"],
      rating: 4.7,
      reviewCount: 120,
      khuyen_mai: "Tặng ROG keychain",
      images: ["images/psu/rog-thor-1.jpg", "images/psu/rog-thor-2.jpg"],
      bao_hanh: "10 năm",
      ngay_phat_hanh: "2022-08-10",
      thiet_bi_tuong_thich: ["ATX 3.0"],
      tinh_nang: ["OLED Display", "Aura Sync", "0dB Technology"],
      danh_muc: "PSU",
    },
    {
      id: "psu005",
      ten: "Cooler Master V850 Gold V2",
      hang: "Cooler Master",
      gia: 3800000,
      thong_so: {
        wattage: "850W",
        efficiency: "80+ Gold",
        modular: "Fully Modular",
        connectors: "ATX 24-pin, 2x EPS, 4x PCIe",
      },
      so_luong: 40,
      mo_ta: "Nguồn hiệu năng cao với giá cả phải chăng...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["PSU", "Cooler Master", "gaming"],
      rating: 4.6,
      reviewCount: 180,
      khuyen_mai: "Giảm 300.000đ khi mua kèm case",
      images: ["images/psu/cm-v850-1.jpg", "images/psu/cm-v850-2.jpg"],
      bao_hanh: "10 năm",
      ngay_phat_hanh: "2021-12-01",
      thiet_bi_tuong_thich: ["ATX 2.4"],
      tinh_nang: ["Semi-fanless", "DC-to-DC", "Japanese Capacitors"],
      danh_muc: "PSU",
    },
    {
      id: "psu006",
      ten: "MSI MPG A750GF",
      hang: "MSI",
      gia: 2900000,
      thong_so: {
        wattage: "750W",
        efficiency: "80+ Gold",
        modular: "Fully Modular",
        connectors: "ATX 24-pin, 2x EPS, 3x PCIe",
      },
      so_luong: 35,
      mo_ta: "Nguồn gaming tầm trung với độ tin cậy cao...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["PSU", "MSI", "gaming", "tầm trung"],
      rating: 4.5,
      reviewCount: 150,
      khuyen_mai: "Tặng dây nguồn premium",
      images: ["images/psu/msi-a750-1.jpg", "images/psu/msi-a750-2.jpg"],
      bao_hanh: "10 năm",
      ngay_phat_hanh: "2021-09-15",
      thiet_bi_tuong_thich: ["ATX 2.4"],
      tinh_nang: ["12V Single Rail", "Zero Fan Mode", "Flat Cables"],
      danh_muc: "PSU",
    },
    {
      id: "psu007",
      ten: "Antec HCG-1000 Extreme",
      hang: "Antec",
      gia: 4500000,
      thong_so: {
        wattage: "1000W",
        efficiency: "80+ Gold",
        modular: "Fully Modular",
        connectors: "ATX 24-pin, 2x EPS, 6x PCIe",
      },
      so_luong: 30,
      mo_ta: "Nguồn công suất cao với độ ổn định tuyệt vời...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["PSU", "Antec", "extreme"],
      rating: 4.6,
      reviewCount: 90,
      khuyen_mai: "Giảm 400.000đ khi mua kèm case Antec",
      images: ["images/psu/antec-hcg-1.jpg", "images/psu/antec-hcg-2.jpg"],
      bao_hanh: "10 năm",
      ngay_phat_hanh: "2022-06-20",
      thiet_bi_tuong_thich: ["ATX 2.4"],
      tinh_nang: ["CircuitShield", "PhaseWave Design", "DBB Bearing Fan"],
      danh_muc: "PSU",
    },
    {
      id: "psu008",
      ten: "EVGA SuperNOVA 850 G6",
      hang: "EVGA",
      gia: 3900000,
      thong_so: {
        wattage: "850W",
        efficiency: "80+ Gold",
        modular: "Fully Modular",
        connectors: "ATX 24-pin, 2x EPS, 4x PCIe",
      },
      so_luong: 45,
      mo_ta: "Nguồn hiệu năng cao với công nghệ ECO Mode...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["PSU", "EVGA", "gaming"],
      rating: 4.7,
      reviewCount: 160,
      khuyen_mai: "Tặng EVGA PowerLink",
      images: ["images/psu/evga-g6-1.jpg", "images/psu/evga-g6-2.jpg"],
      bao_hanh: "10 năm",
      ngay_phat_hanh: "2022-02-15",
      thiet_bi_tuong_thich: ["ATX 2.4"],
      tinh_nang: ["ECO Mode", "Fluid Dynamic Bearing", "EVGA ECO Mode"],
      danh_muc: "PSU",
    },
    {
      id: "psu009",
      ten: "Silverstone SX1000 SFX-L",
      hang: "Silverstone",
      gia: 6500000,
      thong_so: {
        wattage: "1000W",
        efficiency: "80+ Platinum",
        modular: "Fully Modular",
        connectors: "ATX 24-pin, 2x EPS, 4x PCIe",
      },
      so_luong: 20,
      mo_ta: "Nguồn SFX-L công suất cao cho build ITX...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["PSU", "Silverstone", "SFX-L", "ITX"],
      rating: 4.8,
      reviewCount: 70,
      khuyen_mai: "Tặng bộ adapter ATX",
      images: [
        "images/psu/silverstone-sx-1.jpg",
        "images/psu/silverstone-sx-2.jpg",
      ],
      bao_hanh: "5 năm",
      ngay_phat_hanh: "2022-09-01",
      thiet_bi_tuong_thich: ["SFX", "SFX-L"],
      tinh_nang: ["Silent Running", "Multi GPU Support", "Compact Design"],
      danh_muc: "PSU",
    },
    {
      id: "psu010",
      ten: "Thermaltake Toughpower GF3 850W",
      hang: "Thermaltake",
      gia: 4200000,
      thong_so: {
        wattage: "850W",
        efficiency: "80+ Gold",
        modular: "Fully Modular",
        connectors: "ATX 24-pin, 2x EPS, 4x PCIe",
      },
      so_luong: 35,
      mo_ta: "Nguồn ATX 3.0 với hỗ trợ 16-pin cho GPU mới...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["PSU", "Thermaltake", "ATX 3.0"],
      rating: 4.6,
      reviewCount: 95,
      khuyen_mai: "Giảm 300.000đ khi mua kèm case Thermaltake",
      images: [
        "images/psu/thermaltake-gf3-1.jpg",
        "images/psu/thermaltake-gf3-2.jpg",
      ],
      bao_hanh: "10 năm",
      ngay_phat_hanh: "2022-11-10",
      thiet_bi_tuong_thich: ["ATX 3.0", "PCIe 5.0"],
      tinh_nang: ["16-pin Connector", "Smart Zero Fan", "Digital Power"],
      danh_muc: "PSU",
    },
  ],
  cooling: [
    {
      id: "cool001",
      ten: "Noctua NH-D15",
      hang: "Noctua",
      gia: 2500000,
      thong_so: {
        type: "Air Cooler",
        fanSize: "140mm",
        height: "165mm",
        compatibility: "AM4, AM5, LGA 1700",
      },
      so_luong: 35,
      mo_ta:
        "Noctua NH-D15 là tản nhiệt khí cao cấp nổi tiếng với hiệu năng làm mát vượt trội và độ ồn gần như bằng không. Thiết kế dành cho CPU cao cấp như Intel i9-13900K và AMD Ryzen 9 7950X3D, tản nhiệt sử dụng hai quạt 140mm NF-A15 PWM và bộ tản nhiệt tháp đôi lớn để tản nhiệt hiệu quả. Chiều cao 165mm tương thích với hầu hết vỏ case ATX, hỗ trợ socket AM4, AM5 và LGA 1700, phù hợp cho các hệ thống hiện đại. Hệ thống lắp đặt SecuFirm2 dễ dàng và keo tản nhiệt NT-H1 của Noctua đảm bảo truyền nhiệt tối ưu. Lý tưởng cho ép xung hoặc tác vụ nặng như dựng hình video, NH-D15 mang lại hiệu năng ngang ngửa nhiều tản nhiệt nước AIO mà vẫn êm ái. Với bảo hành 6 năm, đây là lựa chọn hàng đầu cho người dùng cần độ tin cậy và làm mát hiệu quả.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["tản nhiệt", "Noctua", "tản nhiệt khí", "êm ái"],
      rating: 4.9,
      reviewCount: 90,
      khuyen_mai: "Tặng kèm keo tản nhiệt Noctua NT-H1",
      images: [
        "images/cooling/noctua-nh-d15-1.jpg",
        "images/cooling/noctua-nh-d15-2.jpg",
      ],
      bao_hanh: "6 năm",
      ngay_phat_hanh: "2014-04-08",
      thiet_bi_tuong_thich: ["CPU AM4, AM5, LGA 1700"],
      tinh_nang: [
        "Thiết kế tháp đôi",
        "Quạt NF-A15 PWM",
        "Hệ thống SecuFirm2",
        "Keo tản nhiệt NT-H1",
      ],
      danh_muc: "Cooling",
    },
    {
      id: "cool002",
      ten: "NZXT Kraken Z73 RGB",
      hang: "NZXT",
      gia: 6500000,
      thong_so: {
        type: "AIO Liquid Cooler",
        radiatorSize: "360mm",
        fanSize: "120mm",
        compatibility: "AM4, AM5, LGA 1700",
      },
      so_luong: 20,
      mo_ta:
        "NZXT Kraken Z73 RGB là tản nhiệt nước AIO 360mm cao cấp dành cho CPU hiệu năng cao trong PC chơi game và máy trạm. Màn hình LCD tùy chỉnh trên bơm hiển thị thông tin hệ thống, ảnh GIF hoặc logo cá nhân. Ba quạt 120mm Aer RGB 2 và két tản nhiệt lớn đảm bảo làm mát vượt trội cho CPU như Ryzen 9 7950X3D hoặc i9-13900K, ngay cả khi ép xung. Tương thích socket AM4, AM5 và LGA 1700, sản phẩm dễ dàng tích hợp vào hệ thống hiện đại. Phần mềm NZXT CAM cho phép điều chỉnh tốc độ quạt, bơm và đèn RGB chính xác. Ống dẫn gia cố và bơm chất lượng cao đảm bảo độ bền và không rò rỉ. Phù hợp cho người dùng muốn kết hợp phong cách và hiệu năng, Kraken Z73 RGB mang lại làm mát êm ái, hiệu quả và vẻ đẹp độc đáo, với bảo hành 6 năm.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["tản nhiệt", "NZXT", "AIO", "RGB"],
      rating: 4.8,
      reviewCount: 110,
      khuyen_mai: "Tặng bộ điều khiển RGB NZXT",
      images: [
        "images/cooling/nzxt-kraken-z73-1.jpg",
        "images/cooling/nzxt-kraken-z73-2.jpg",
      ],
      bao_hanh: "6 năm",
      ngay_phat_hanh: "2020-02-11",
      thiet_bi_tuong_thich: ["CPU AM4, AM5, LGA 1700"],
      tinh_nang: [
        "Màn hình LCD tùy chỉnh",
        "Quạt Aer RGB 2",
        "Phần mềm NZXT CAM",
        "Két tản nhiệt 360mm",
      ],
      danh_muc: "Cooling",
    },

    {
      id: "cool003",
      ten: "Arctic Liquid Freezer II 360",
      hang: "Arctic",
      gia: 3800000,
      thong_so: {
        type: "AIO Liquid Cooler",
        radiatorSize: "360mm",
        fanSize: "120mm",
        compatibility: "AM4, AM5, LGA 1700",
      },
      so_luong: 30,
      mo_ta: "Tản nhiệt nước AIO hiệu năng cao với giá tốt...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["Arctic", "AIO", "360mm", "giá tốt"],
      rating: 4.8,
      reviewCount: 220,
      khuyen_mai: "Tặng kèm thermal paste MX-4",
      images: [
        "images/cooling/arctic-360-1.jpg",
        "images/cooling/arctic-360-2.jpg",
      ],
      bao_hanh: "6 năm",
      ngay_phat_hanh: "2021-05-15",
      thiet_bi_tuong_thich: ["CPU AMD & Intel"],
      tinh_nang: ["VRM Fan", "PWM Control", "Offset Mount"],
      danh_muc: "Cooling",
    },
    {
      id: "cool004",
      ten: "DeepCool AK620",
      hang: "DeepCool",
      gia: 1800000,
      thong_so: {
        type: "Air Cooler",
        fanSize: "120mm",
        height: "160mm",
        compatibility: "AM4, AM5, LGA 1700",
      },
      so_luong: 45,
      mo_ta: "Tản nhiệt khí dual-tower giá rẻ hiệu năng cao...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["DeepCool", "Air Cooler", "giá rẻ"],
      rating: 4.6,
      reviewCount: 180,
      khuyen_mai: "Giảm 100.000đ khi mua kèm case",
      images: [
        "images/cooling/deepcool-ak620-1.jpg",
        "images/cooling/deepcool-ak620-2.jpg",
      ],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-01-20",
      thiet_bi_tuong_thich: ["CPU AMD & Intel"],
      tinh_nang: ["6 Heatpipes", "Matrix Fin Array", "FK120 Fan"],
      danh_muc: "Cooling",
    },
    {
      id: "cool005",
      ten: "Corsair iCUE H150i ELITE LCD",
      hang: "Corsair",
      gia: 7500000,
      thong_so: {
        type: "AIO Liquid Cooler",
        radiatorSize: "360mm",
        fanSize: "120mm",
        compatibility: "AM4, AM5, LGA 1700",
      },
      so_luong: 20,
      mo_ta: "Tản nhiệt nước cao cấp với màn hình LCD tùy chỉnh...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["Corsair", "AIO", "LCD", "cao cấp"],
      rating: 4.9,
      reviewCount: 150,
      khuyen_mai: "Tặng Commander Core XT",
      images: [
        "images/cooling/corsair-h150i-1.jpg",
        "images/cooling/corsair-h150i-2.jpg",
      ],
      bao_hanh: "5 năm",
      ngay_phat_hanh: "2022-03-10",
      thiet_bi_tuong_thich: ["CPU AMD & Intel"],
      tinh_nang: ["IPS LCD Screen", "iCUE Control", "ML RGB ELITE fans"],
      danh_muc: "Cooling",
    },
    {
      id: "cool006",
      ten: "Scythe Fuma 2 Rev.B",
      hang: "Scythe",
      gia: 2200000,
      thong_so: {
        type: "Air Cooler",
        fanSize: "120mm",
        height: "154.5mm",
        compatibility: "AM4, AM5, LGA 1700",
      },
      so_luong: 35,
      mo_ta: "Tản nhiệt khí dual-tower với thiết kế tối ưu RAM clearance...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["Scythe", "Air Cooler", "silent"],
      rating: 4.7,
      reviewCount: 130,
      khuyen_mai: "Tặng keo tản nhiệt Thermal Grizzly",
      images: [
        "images/cooling/scythe-fuma2-1.jpg",
        "images/cooling/scythe-fuma2-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2022-06-15",
      thiet_bi_tuong_thich: ["CPU AMD & Intel"],
      tinh_nang: ["Asymmetric Design", "Dual Kaze Flex Fans", "6 Heatpipes"],
      danh_muc: "Cooling",
    },
    {
      id: "cool007",
      ten: "Lian Li Galahad SL120 360",
      hang: "Lian Li",
      gia: 4500000,
      thong_so: {
        type: "AIO Liquid Cooler",
        radiatorSize: "360mm",
        fanSize: "120mm",
        compatibility: "AM4, AM5, LGA 1700",
      },
      so_luong: 25,
      mo_ta: "Tản nhiệt nước với thiết kế quạt SL độc quyền không dây...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["Lian Li", "AIO", "RGB"],
      rating: 4.8,
      reviewCount: 110,
      khuyen_mai: "Tặng 3 quạt SL120",
      images: [
        "images/cooling/lianli-galahad-1.jpg",
        "images/cooling/lianli-galahad-2.jpg",
      ],
      bao_hanh: "5 năm",
      ngay_phat_hanh: "2022-08-20",
      thiet_bi_tuong_thich: ["CPU AMD & Intel"],
      tinh_nang: ["Daisy Chain", "L-Connect Control", "Infinity Mirror"],
      danh_muc: "Cooling",
    },
    {
      id: "cool008",
      ten: "Thermalright Peerless Assassin 120",
      hang: "Thermalright",
      gia: 1200000,
      thong_so: {
        type: "Air Cooler",
        fanSize: "120mm",
        height: "157mm",
        compatibility: "AM4, AM5, LGA 1700",
      },
      so_luong: 50,
      mo_ta: "Tản nhiệt khí giá rẻ hiệu năng tốt...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["Thermalright", "Air Cooler", "giá rẻ"],
      rating: 4.5,
      reviewCount: 200,
      khuyen_mai: "Giảm 100.000đ khi mua kèm paste",
      images: [
        "images/cooling/thermalright-pa120-1.jpg",
        "images/cooling/thermalright-pa120-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2022-02-10",
      thiet_bi_tuong_thich: ["CPU AMD & Intel"],
      tinh_nang: ["6 Heatpipes", "TL-C12 PWM Fan", "Dual Tower"],
      danh_muc: "Cooling",
    },
    {
      id: "cool009",
      ten: "MSI MEG CORELIQUID S360",
      hang: "MSI",
      gia: 6800000,
      thong_so: {
        type: "AIO Liquid Cooler",
        radiatorSize: "360mm",
        fanSize: "120mm",
        compatibility: "AM4, AM5, LGA 1700",
      },
      so_luong: 15,
      mo_ta:
        "Tản nhiệt nước cao cấp với màn hình LCD và quạt Silent Gale P12...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["MSI", "AIO", "LCD", "cao cấp"],
      rating: 4.7,
      reviewCount: 85,
      khuyen_mai: "Tặng MSI Gaming Mouse",
      images: [
        "images/cooling/msi-s360-1.jpg",
        "images/cooling/msi-s360-2.jpg",
      ],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2022-07-15",
      thiet_bi_tuong_thich: ["CPU AMD & Intel"],
      tinh_nang: ['2.4" LCD Screen', "Silent Gale P12", "Zero RPM Mode"],
      danh_muc: "Cooling",
    },
    {
      id: "cool010",
      ten: "Be Quiet! Pure Rock 2",
      hang: "Be Quiet!",
      gia: 900000,
      thong_so: {
        type: "Air Cooler",
        fanSize: "120mm",
        height: "155mm",
        compatibility: "AM4, AM5, LGA 1700",
      },
      so_luong: 60,
      mo_ta: "Tản nhiệt khí entry-level yên tĩnh và hiệu quả...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["Be Quiet!", "Air Cooler", "silent"],
      rating: 4.4,
      reviewCount: 250,
      khuyen_mai: "Giảm giá khi mua kèm case Be Quiet!",
      images: [
        "images/cooling/pure-rock2-1.jpg",
        "images/cooling/pure-rock2-2.jpg",
      ],
      bao_hanh: "3 năm",
      ngay_phat_hanh: "2021-09-10",
      thiet_bi_tuong_thich: ["CPU AMD & Intel"],
      tinh_nang: ["4 Heatpipes", "Pure Wings 2", "High Ram Clearance"],
      danh_muc: "Cooling",
    },
  ],
  case: [
    {
      id: "case001",
      ten: "Lian Li PC-O11 Dynamic",
      hang: "Lian Li",
      gia: 3500000,
      thong_so: {
        type: "Mid Tower",
        material: "Steel, Tempered Glass",
        motherboardSupport: "ATX, Micro-ATX, Mini-ITX",
        dimensions: "446 x 272 x 445 mm",
      },
      so_luong: 15,
      mo_ta:
        "Lian Li PC-O11 Dynamic là vỏ case mid-tower cao cấp dành cho người dùng muốn kết hợp phong cách và chức năng. Với hai mặt kính cường lực, case khoe trọn linh kiện và đèn RGB bên trong. Không gian rộng rãi hỗ trợ bo mạch chủ ATX, Micro-ATX và Mini-ITX, cùng với GPU lớn, nhiều ổ cứng và hệ thống tản nhiệt nước phức tạp. Thiết kế hai khoang tách biệt PSU và cáp, giúp quản lý cáp gọn gàng và cải thiện luồng khí. Hỗ trợ tối đa 9 quạt hoặc két tản nhiệt 360mm, case đảm bảo làm mát hiệu quả cho linh kiện như RTX 4090. Kết cấu nhôm và thép bền bỉ, mang lại vẻ đẹp hiện đại. Phù hợp cho PC chơi game hoặc máy trạm, PC-O11 Dynamic cung cấp sự linh hoạt, dễ nâng cấp và thẩm mỹ ấn tượng, là lựa chọn yêu thích của người lắp ráp PC.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["vỏ case", "LianLi", "mid-tower", "RGB"],
      rating: 4.8,
      reviewCount: 60,
      khuyen_mai: "Tặng 2 quạt RGB khi mua case",
      images: [
        "images/case/lian-li-o11-1.jpg",
        "images/case/lian-li-o11-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2018-05-15",
      thiet_bi_tuong_thich: ["Bo mạch chủ ATX", "Két tản nhiệt 360mm"],
      tinh_nang: [
        "Mặt kính cường lực đôi",
        "Thiết kế hai khoang",
        "Hỗ trợ tản nhiệt nước",
        "Quản lý cáp",
      ],
      danh_muc: "Case",
    },
    {
      id: "case002",
      ten: "Fractal Design Meshify 2",
      hang: "Fractal Design",
      gia: 3200000,
      thong_so: {
        type: "Mid Tower",
        material: "Steel, Mesh, Tempered Glass",
        motherboardSupport: "ATX, Micro-ATX, Mini-ITX",
        dimensions: "474 x 210 x 454 mm",
      },
      so_luong: 18,
      mo_ta:
        "Fractal Design Meshify 2 là vỏ case mid-tower tối ưu luồng khí, kết hợp hiệu năng và phong cách tối giản. Mặt trước lưới góc cạnh tăng cường luồng khí, đảm bảo làm mát tối ưu cho linh kiện cao cấp như Ryzen 9 hoặc RTX 4090. Hỗ trợ bo mạch chủ ATX, Micro-ATX và Mini-ITX, case cung cấp không gian cho tối đa 7 quạt, két tản nhiệt 360mm và nhiều ổ cứng, với thiết kế mô-đun dễ tùy chỉnh. Mặt kính cường lực khoe linh kiện bên trong, trong khi thiết kế không cần dụng cụ giúp nâng cấp dễ dàng. Quản lý cáp được tối ưu với kênh và dây đai Velcro. Phù hợp cho PC chơi game hoặc máy trạm, Meshify 2 mang lại kết cấu thép bền bỉ, hiệu năng tản nhiệt vượt trội và thẩm mỹ Bắc Âu tinh tế, là lựa chọn lý tưởng cho người dùng ưu tiên luồng khí và chức năng.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["vỏ case", "FractalDesign", "mid-tower", "luồng khí"],
      rating: 4.7,
      reviewCount: 80,
      khuyen_mai: "Tặng bộ lọc bụi khi mua",
      images: [
        "images/case/fractal-meshify-2-1.jpg",
        "images/case/fractal-meshify-2-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2020-08-18",
      thiet_bi_tuong_thich: ["Bo mạch chủ ATX", "Két tản nhiệt 360mm"],
      tinh_nang: [
        "Lưới luồng khí cao",
        "Mặt kính cường lực",
        "Thiết kế mô-đun",
        "Quản lý cáp",
      ],
      danh_muc: "Case",
    },

    {
      id: "case003",
      ten: "NZXT H7 Elite",
      hang: "NZXT",
      gia: 4500000,
      thong_so: {
        type: "Mid Tower",
        material: "Steel, Tempered Glass",
        motherboardSupport: "ATX, Micro-ATX, Mini-ITX",
        dimensions: "505 x 230 x 480 mm",
      },
      so_luong: 25,
      mo_ta:
        "Case mid-tower cao cấp với mặt kính cường lực và hệ thống RGB tích hợp...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["NZXT", "mid-tower", "RGB"],
      rating: 4.8,
      reviewCount: 120,
      khuyen_mai: "Tặng 3 quạt RGB F120",
      images: [
        "images/case/nzxt-h7-elite-1.jpg",
        "images/case/nzxt-h7-elite-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2022-06-15",
      thiet_bi_tuong_thich: ["Bo mạch chủ ATX", "Tản nhiệt 360mm"],
      tinh_nang: ["Kính cường lực", "Hỗ trợ RGB", "Quản lý cáp tối ưu"],
      danh_muc: "Case",
    },
    {
      id: "case004",
      ten: "Corsair 4000D Airflow",
      hang: "Corsair",
      gia: 2000000,
      thong_so: {
        type: "Mid Tower",
        material: "Steel, Tempered Glass",
        motherboardSupport: "ATX, Micro-ATX, Mini-ITX",
        dimensions: "453 x 230 x 466 mm",
      },
      so_luong: 50,
      mo_ta: "Case mid-tower giá rẻ với thiết kế tối ưu luồng khí...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["Corsair", "mid-tower", "airflow"],
      rating: 4.7,
      reviewCount: 180,
      khuyen_mai: "Tặng quạt SP120 RGB",
      images: [
        "images/case/corsair-4000d-1.jpg",
        "images/case/corsair-4000d-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2021-08-10",
      thiet_bi_tuong_thich: ["Bo mạch chủ ATX", "Tản nhiệt 280mm"],
      tinh_nang: ["Luồng khí tối ưu", "Kính cường lực", "Quản lý cáp dễ dàng"],
      danh_muc: "Case",
    },
    {
      id: "case005",
      ten: "Phanteks Eclipse P500A",
      hang: "Phanteks",
      gia: 3000000,
      thong_so: {
        type: "Mid Tower",
        material: "Steel, Mesh, Tempered Glass",
        motherboardSupport: "E-ATX, ATX, Micro-ATX, Mini-ITX",
        dimensions: "510 x 240 x 505 mm",
      },
      so_luong: 30,
      mo_ta: "Case mid-tower với mặt lưới tối ưu luồng khí và hỗ trợ E-ATX...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["Phanteks", "mid-tower", "E-ATX"],
      rating: 4.8,
      reviewCount: 140,
      khuyen_mai: "Tặng quạt D-RGB",
      images: [
        "images/case/phanteks-p500a-1.jpg",
        "images/case/phanteks-p500a-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2021-09-15",
      thiet_bi_tuong_thich: ["Bo mạch chủ E-ATX", "Tản nhiệt 360mm"],
      tinh_nang: ["Luồng khí tối ưu", "Hỗ trợ E-ATX", "Kính cường lực"],
      danh_muc: "Case",
    },
    {
      id: "case006",
      ten: "Cooler Master MasterBox TD500 Mesh",
      hang: "Cooler Master",
      gia: 2500000,
      thong_so: {
        type: "Mid Tower",
        material: "Steel, Mesh, Tempered Glass",
        motherboardSupport: "ATX, Micro-ATX, Mini-ITX",
        dimensions: "493 x 217 x 469 mm",
      },
      so_luong: 40,
      mo_ta: "Case mid-tower với thiết kế mặt lưới 3D độc đáo...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["Cooler Master", "mid-tower", "mesh"],
      rating: 4.6,
      reviewCount: 160,
      khuyen_mai: "Tặng quạt ARGB MF120",
      images: ["images/case/cm-td500-1.jpg", "images/case/cm-td500-2.jpg"],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2021-07-20",
      thiet_bi_tuong_thich: ["Bo mạch chủ ATX", "Tản nhiệt 360mm"],
      tinh_nang: ["Mặt lưới 3D", "ARGB Sync", "Quản lý cáp dễ dàng"],
      danh_muc: "Case",
    },
    {
      id: "case007",
      ten: "Thermaltake Core P3 TG Pro",
      hang: "Thermaltake",
      gia: 4000000,
      thong_so: {
        type: "Open Frame",
        material: "Steel, Tempered Glass",
        motherboardSupport: "ATX, Micro-ATX, Mini-ITX",
        dimensions: "512 x 333 x 470 mm",
      },
      so_luong: 20,
      mo_ta: "Case open-frame với thiết kế kính cường lực toàn diện...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["Thermaltake", "open-frame", "kính cường lực"],
      rating: 4.7,
      reviewCount: 100,
      khuyen_mai: "Tặng giá đỡ GPU",
      images: ["images/case/tt-core-p3-1.jpg", "images/case/tt-core-p3-2.jpg"],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2022-03-15",
      thiet_bi_tuong_thich: ["Bo mạch chủ ATX", "Tản nhiệt 420mm"],
      tinh_nang: ["Open Frame", "Kính cường lực", "Hỗ trợ tản nhiệt nước"],
      danh_muc: "Case",
    },
    {
      id: "case008",
      ten: "Fractal Design Define 7 Compact",
      hang: "Fractal Design",
      gia: 3500000,
      thong_so: {
        type: "Mid Tower",
        material: "Steel, Tempered Glass",
        motherboardSupport: "ATX, Micro-ATX, Mini-ITX",
        dimensions: "427 x 210 x 474 mm",
      },
      so_luong: 30,
      mo_ta: "Case mid-tower nhỏ gọn với thiết kế cách âm...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["Fractal Design", "mid-tower", "cách âm"],
      rating: 4.8,
      reviewCount: 110,
      khuyen_mai: "Tặng bộ lọc bụi",
      images: [
        "images/case/fractal-define7-1.jpg",
        "images/case/fractal-define7-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2021-11-10",
      thiet_bi_tuong_thich: ["Bo mạch chủ ATX", "Tản nhiệt 280mm"],
      tinh_nang: ["Cách âm", "Kính cường lực", "Quản lý cáp tối ưu"],
      danh_muc: "Case",
    },
    {
      id: "case009",
      ten: "Lian Li Lancool III",
      hang: "Lian Li",
      gia: 3200000,
      thong_so: {
        type: "Mid Tower",
        material: "Steel, Tempered Glass",
        motherboardSupport: "E-ATX, ATX, Micro-ATX, Mini-ITX",
        dimensions: "526 x 238 x 523 mm",
      },
      so_luong: 35,
      mo_ta: "Case mid-tower với thiết kế tối ưu cho tản nhiệt nước...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["Lian Li", "mid-tower", "E-ATX"],
      rating: 4.7,
      reviewCount: 140,
      khuyen_mai: "Tặng 3 quạt ARGB",
      images: [
        "images/case/lianli-lancool3-1.jpg",
        "images/case/lianli-lancool3-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2022-07-15",
      thiet_bi_tuong_thich: ["Bo mạch chủ E-ATX", "Tản nhiệt 420mm"],
      tinh_nang: ["Hỗ trợ E-ATX", "ARGB Sync", "Quản lý cáp dễ dàng"],
      danh_muc: "Case",
    },
    {
      id: "case010",
      ten: "SilverStone FARA R1",
      hang: "SilverStone",
      gia: 1500000,
      thong_so: {
        type: "Mid Tower",
        material: "Steel, Mesh, Tempered Glass",
        motherboardSupport: "ATX, Micro-ATX, Mini-ITX",
        dimensions: "446 x 207 x 390 mm",
      },
      so_luong: 60,
      mo_ta: "Case mid-tower giá rẻ với thiết kế tối ưu luồng khí...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["SilverStone", "mid-tower", "giá rẻ"],
      rating: 4.5,
      reviewCount: 200,
      khuyen_mai: "Giảm giá khi mua kèm PSU SilverStone",
      images: [
        "images/case/silverstone-fara-1.jpg",
        "images/case/silverstone-fara-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2021-05-20",
      thiet_bi_tuong_thich: ["Bo mạch chủ ATX", "Tản nhiệt 280mm"],
      tinh_nang: ["Luồng khí tối ưu", "Kính cường lực", "Quản lý cáp dễ dàng"],
      danh_muc: "Case",
    },
  ],
  peripherals: [
    {
      id: "mouse001",
      ten: "Logitech G Pro X Superlight",
      hang: "Logitech",
      gia: 3750000,
      thong_so: {
        type: "Wireless Mouse",
        sensor: "HERO 25K",
        dpi: "100-25600",
        weight: "63g",
        connectivity: "USB Receiver, Wireless",
      },
      so_luong: 80,
      mo_ta:
        "Logitech G Pro X Superlight là chuột chơi game không dây siêu nhẹ dành cho các game thủ esports và thi đấu chuyên nghiệp. Với trọng lượng chỉ 63g, chuột đảm bảo di chuyển nhanh và chính xác, trong khi cảm biến HERO 25K cung cấp độ chính xác vượt trội với dải DPI 100-25600. Công nghệ không dây Lightspeed cho độ trễ thấp, mang lại trải nghiệm tương đương chuột có dây. Thiết kế tối giản với 5 nút lập trình và hình dáng cân đối, thoải mái cho các phiên chơi dài. Tương thích với phần mềm Logitech G Hub, chuột cho phép tùy chỉnh DPI, nút và tốc độ phản hồi. Lý tưởng cho các game tốc độ cao như Valorant hoặc CS:GO, Superlight có pin 70 giờ và chân đế PTFE mượt mà. Với thiết kế cao cấp và hiệu năng đỉnh cao, đây là lựa chọn hàng đầu cho game thủ cần tốc độ và độ chính xác.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["chuột", "không dây", "Logitech", "esports"],
      rating: 4.9,
      reviewCount: 300,
      khuyen_mai: "Giảm 10% khi mua cùng bàn phím Logitech",
      images: [
        "images/peripherals/logitech-g-pro-x-superlight-1.jpg",
        "images/peripherals/logitech-g-pro-x-superlight-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2020-12-08",
      thiet_bi_tuong_thich: ["Windows, macOS"],
      tinh_nang: [
        "Cảm biến HERO 25K",
        "Không dây Lightspeed",
        "Siêu nhẹ",
        "Chân đế PTFE",
      ],
      danh_muc: "Peripherals",
    },
    {
      id: "kb001",
      ten: "Keychron K8 Pro",
      hang: "Keychron",
      gia: 2500000,
      thong_so: {
        type: "Mechanical Keyboard",
        switchType: "Gateron Red",
        layout: "Tenkeyless",
        connectivity: "USB-C, Bluetooth",
        backlighting: "RGB",
      },
      so_luong: 45,
      mo_ta:
        "Keychron K8 Pro là bàn phím cơ tenkeyless linh hoạt dành cho game thủ, người gõ phím và chuyên gia. Với switch Gateron Red có thể thay nóng, bàn phím mang lại trải nghiệm gõ mượt mà, tuyến tính và dễ dàng tùy chỉnh mà không cần hàn. Kết nối Bluetooth 5.1 và USB-C hỗ trợ chuyển đổi giữa ba thiết bị, lý tưởng cho đa nhiệm trên Windows, macOS và Linux. Đèn RGB tùy chỉnh qua phần mềm QMK/VIA nâng cao tính thẩm mỹ và khả năng sử dụng. Khung nhôm chắc chắn và keycap ABS cân bằng độ bền và tính di động. Pin 4000mAh cho thời gian sử dụng không dây lên đến 100 giờ. Phù hợp cho chơi game, lập trình hoặc công việc, K8 Pro mang lại trải nghiệm gõ cao cấp với độ trễ thấp và khả năng tùy chỉnh sâu, đáp ứng nhu cầu của người dùng muốn linh hoạt và hiệu năng.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["bàn phím", "cơ học", "Keychron", "không dây"],
      rating: 4.8,
      reviewCount: 220,
      khuyen_mai: "Giảm 5% khi mua kèm chuột Logitech",
      images: [
        "images/peripherals/keychron-k8-pro-1.jpg",
        "images/peripherals/keychron-k8-pro-2.jpg",
      ],
      bao_hanh: "1 năm",
      ngay_phat_hanh: "2022-07-20",
      thiet_bi_tuong_thich: ["Windows, macOS, Linux"],
      tinh_nang: [
        "Switch thay nóng",
        "Bluetooth 5.1",
        "Đèn RGB",
        "Hỗ trợ QMK/VIA",
      ],
      danh_muc: "Peripherals",
    },
    {
      id: "mouse002",
      ten: "Razer DeathAdder V3 Pro",
      hang: "Razer",
      gia: 4000000,
      thong_so: {
        type: "Wireless Mouse",
        sensor: "Focus Pro 30K",
        dpi: "100-30000",
        weight: "63g",
        connectivity: "USB-C, Wireless",
      },
      so_luong: 50,
      mo_ta:
        "Razer DeathAdder V3 Pro là chuột chơi game không dây siêu nhẹ dành cho esports và thi đấu chuyên nghiệp. Với trọng lượng 63g, chuột sử dụng cảm biến quang học Focus Pro 30K của Razer, mang lại độ chính xác vượt trội với dải DPI 100-30000. Công nghệ HyperSpeed Wireless đảm bảo độ trễ thấp, trong khi thiết kế công thái học mang lại sự thoải mái cho các phiên chơi dài. Với 6 nút lập trình và phần mềm Razer Synapse, chuột cho phép tùy chỉnh sâu cho các game như Overwatch hoặc Apex Legends. Pin 90 giờ và cáp sạc USB-C đảm bảo sử dụng liên tục. Switch quang học bền bỉ với 90 triệu lần nhấn và chân đế PTFE cho độ trượt mượt mà. Lý tưởng cho game thủ cần độ chính xác và tốc độ, DeathAdder V3 Pro kết hợp công nghệ tiên tiến với thiết kế mang tính biểu tượng của Razer, là lựa chọn cao cấp cho hiệu năng thi đấu.",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["chuột", "không dây", "Razer", "esports"],
      rating: 4.9,
      reviewCount: 200,
      khuyen_mai: "Tặng lót chuột Razer khi mua",
      images: [
        "images/peripherals/razer-deathadder-v3-1.jpg",
        "images/peripherals/razer-deathadder-v3-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2022-08-11",
      thiet_bi_tuong_thich: ["Windows, macOS"],
      tinh_nang: [
        "Cảm biến Focus Pro 30K",
        "Không dây HyperSpeed",
        "Switch quang học",
        "Thiết kế công thái học",
      ],
      danh_muc: "Peripherals",
    },

    {
      id: "peripheral003",
      ten: "Razer BlackWidow V4 Pro",
      hang: "Razer",
      gia: 4500000,
      thong_so: {
        type: "Mechanical Keyboard",
        switchType: "Razer Green",
        layout: "Full-size",
        connectivity: "USB-C",
        backlighting: "RGB Chroma",
      },
      so_luong: 30,
      mo_ta: "Bàn phím cơ cao cấp với switch Razer Green và đèn RGB Chroma...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["bàn phím", "Razer", "RGB", "cao cấp"],
      rating: 4.8,
      reviewCount: 150,
      khuyen_mai: "Tặng kê tay Razer",
      images: [
        "images/peripherals/razer-blackwidow-1.jpg",
        "images/peripherals/razer-blackwidow-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2023-02-15",
      thiet_bi_tuong_thich: ["Windows, macOS"],
      tinh_nang: ["Switch cơ học Razer", "RGB Chroma", "Macro Keys"],
      danh_muc: "Peripherals",
    },
    {
      id: "peripheral004",
      ten: "Logitech MX Master 3S",
      hang: "Logitech",
      gia: 2500000,
      thong_so: {
        type: "Wireless Mouse",
        sensor: "Darkfield",
        dpi: "200-8000",
        weight: "141g",
        connectivity: "Bluetooth, USB Receiver",
      },
      so_luong: 40,
      mo_ta:
        "Chuột không dây cao cấp dành cho công việc với thiết kế công thái học...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["chuột", "Logitech", "công thái học"],
      rating: 4.9,
      reviewCount: 200,
      khuyen_mai: "Tặng túi đựng Logitech",
      images: [
        "images/peripherals/logitech-mx-master-1.jpg",
        "images/peripherals/logitech-mx-master-2.jpg",
      ],
      bao_hanh: "1 năm",
      ngay_phat_hanh: "2022-09-10",
      thiet_bi_tuong_thich: ["Windows, macOS, Linux"],
      tinh_nang: ["Công thái học", "Cuộn từ tính", "Sạc USB-C"],
      danh_muc: "Peripherals",
    },
    {
      id: "peripheral005",
      ten: "SteelSeries Apex Pro TKL",
      hang: "SteelSeries",
      gia: 4000000,
      thong_so: {
        type: "Mechanical Keyboard",
        switchType: "OmniPoint Adjustable",
        layout: "Tenkeyless",
        connectivity: "USB-C",
        backlighting: "RGB",
      },
      so_luong: 35,
      mo_ta:
        "Bàn phím cơ TKL với switch OmniPoint tùy chỉnh hành trình phím...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["bàn phím", "SteelSeries", "RGB", "TKL"],
      rating: 4.8,
      reviewCount: 120,
      khuyen_mai: "Tặng keycap PBT",
      images: [
        "images/peripherals/steelseries-apex-1.jpg",
        "images/peripherals/steelseries-apex-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2022-11-20",
      thiet_bi_tuong_thich: ["Windows, macOS"],
      tinh_nang: ["Switch OmniPoint", "RGB", "OLED Display"],
      danh_muc: "Peripherals",
    },
    {
      id: "peripheral006",
      ten: "Corsair K70 RGB MK.2",
      hang: "Corsair",
      gia: 3500000,
      thong_so: {
        type: "Mechanical Keyboard",
        switchType: "Cherry MX Red",
        layout: "Full-size",
        connectivity: "USB",
        backlighting: "RGB",
      },
      so_luong: 50,
      mo_ta:
        "Bàn phím cơ gaming với switch Cherry MX Red và đèn RGB sống động...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["bàn phím", "Corsair", "RGB", "gaming"],
      rating: 4.7,
      reviewCount: 180,
      khuyen_mai: "Tặng kê tay Corsair",
      images: [
        "images/peripherals/corsair-k70-1.jpg",
        "images/peripherals/corsair-k70-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2021-10-15",
      thiet_bi_tuong_thich: ["Windows"],
      tinh_nang: ["Switch Cherry MX", "RGB", "Macro Keys"],
      danh_muc: "Peripherals",
    },
    {
      id: "peripheral007",
      ten: "HyperX Pulsefire Haste",
      hang: "HyperX",
      gia: 1200000,
      thong_so: {
        type: "Wired Mouse",
        sensor: "Pixart 3335",
        dpi: "400-16000",
        weight: "59g",
        connectivity: "USB",
      },
      so_luong: 60,
      mo_ta: "Chuột gaming siêu nhẹ với thiết kế tổ ong và hiệu năng cao...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["chuột", "HyperX", "siêu nhẹ"],
      rating: 4.6,
      reviewCount: 140,
      khuyen_mai: "Tặng feet chuột HyperX",
      images: [
        "images/peripherals/hyperx-haste-1.jpg",
        "images/peripherals/hyperx-haste-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2021-09-01",
      thiet_bi_tuong_thich: ["Windows, macOS"],
      tinh_nang: ["Siêu nhẹ", "Switch TTC Golden", "Cáp HyperFlex"],
      danh_muc: "Peripherals",
    },
    {
      id: "peripheral008",
      ten: "Logitech G502 X Plus",
      hang: "Logitech",
      gia: 3000000,
      thong_so: {
        type: "Wireless Mouse",
        sensor: "HERO 25K",
        dpi: "100-25600",
        weight: "106g",
        connectivity: "USB Receiver, Bluetooth",
      },
      so_luong: 45,
      mo_ta: "Chuột gaming không dây cao cấp với thiết kế công thái học...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["chuột", "Logitech", "gaming"],
      rating: 4.8,
      reviewCount: 170,
      khuyen_mai: "Tặng lót chuột Logitech",
      images: [
        "images/peripherals/logitech-g502x-1.jpg",
        "images/peripherals/logitech-g502x-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2022-10-01",
      thiet_bi_tuong_thich: ["Windows, macOS"],
      tinh_nang: ["HERO 25K Sensor", "Lightspeed Wireless", "RGB"],
      danh_muc: "Peripherals",
    },
    {
      id: "peripheral009",
      ten: "Keychron K6",
      hang: "Keychron",
      gia: 2000000,
      thong_so: {
        type: "Mechanical Keyboard",
        switchType: "Gateron Brown",
        layout: "Compact 65%",
        connectivity: "Bluetooth, USB-C",
        backlighting: "White LED",
      },
      so_luong: 50,
      mo_ta: "Bàn phím cơ không dây nhỏ gọn với thiết kế 65%...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["bàn phím", "Keychron", "compact"],
      rating: 4.7,
      reviewCount: 190,
      khuyen_mai: "Tặng keycap PBT",
      images: [
        "images/peripherals/keychron-k6-1.jpg",
        "images/peripherals/keychron-k6-2.jpg",
      ],
      bao_hanh: "1 năm",
      ngay_phat_hanh: "2021-11-20",
      thiet_bi_tuong_thich: ["Windows, macOS"],
      tinh_nang: ["Switch thay nóng", "Bluetooth 5.1", "Compact Layout"],
      danh_muc: "Peripherals",
    },
    {
      id: "peripheral010",
      ten: "Razer Basilisk V3 Pro",
      hang: "Razer",
      gia: 3500000,
      thong_so: {
        type: "Wireless Mouse",
        sensor: "Focus Pro 30K",
        dpi: "100-30000",
        weight: "112g",
        connectivity: "USB Receiver, Bluetooth",
      },
      so_luong: 40,
      mo_ta:
        "Chuột gaming không dây với thiết kế công thái học và hiệu năng cao...",
      trang_thai: "Còn hàng",
      updatedAt: "2025-04-26",
      tags: ["chuột", "Razer", "gaming"],
      rating: 4.9,
      reviewCount: 180,
      khuyen_mai: "Tặng dock sạc Razer",
      images: [
        "images/peripherals/razer-basilisk-1.jpg",
        "images/peripherals/razer-basilisk-2.jpg",
      ],
      bao_hanh: "2 năm",
      ngay_phat_hanh: "2022-12-01",
      thiet_bi_tuong_thich: ["Windows, macOS"],
      tinh_nang: ["Focus Pro Sensor", "HyperSpeed Wireless", "RGB Chroma"],
      danh_muc: "Peripherals",
    },
  ],
};

export default products;
